import type { BootcampLevel, CheckState, TensorNode } from "./workbenchTypes";

type NodeSpec = Omit<TensorNode, "stats" | "sample" | "checks"> & {
  stats?: TensorNode["stats"];
  sample?: string[];
  checks?: TensorNode["checks"];
};

const defaultStats = { min: "-", max: "-", mean: "-" };

function makeNode(spec: NodeSpec): TensorNode {
  return {
    ...spec,
    stats: spec.stats ?? defaultStats,
    sample: spec.sample ?? [],
    checks: spec.checks ?? [{ label: "inspectable", state: "pass", detail: "click to inspect shape, dtype, and sample values" }]
  };
}

function check(label: string, state: CheckState, detail: string) {
  return { label, state, detail };
}

export const transposeTrapLevel: BootcampLevel = {
  id: "0-3",
  title: "Transpose Trap",
  subtitle: "Build QK^T from axis contracts",
  objective:
    "按 0-3A 到 0-3X 的阶梯挑战，从二维矩阵转置推进到多头 QK^T，并通过 T==D 数值陷阱和隐藏测试。",
  sceneTitle: "Chapter 0-3 - Transpose Trap",
  sceneSubtitle: "Challenge ladder: matrix flip, inner-dim repair, higher-rank axis swap, QK score boards, debugger, and gauntlet.",
  defaultSelectedNodeId: "matrix_plate",
  briefing: [
    "上一关你已经知道 MatMul 消费内维度。现在要修复方向：有些张量不能直接相乘，必须先交换轴。",
    "Transpose 不是随机洗牌，也不是只改 shape 标签；它必须保持数值坐标映射。",
    "Attention 的 QK^T 本质是让 Query token 行与 Key token 列相遇，生成 token-to-token score board。"
  ],
  knowledgeCards: [
    {
      title: "0-3 Transpose Trap",
      body: "这一关不要求你背 QK^T 公式。\n\n你会先亲手翻转二维矩阵，再把同一个规则扩展到高阶 tensor 和 attention scores。",
      visual: ["matrix[R,C] -> matrix^T[C,R]", "A[M,N] @ B^T[N,P]", "Q[T,D] @ K^T[D,T]", "scores[T,T]"]
    },
    {
      title: "Transpose 是轴交换",
      body: "真正的 transpose 会交换轴和数值索引。\n\n如果 A[i,j] 出现在 A^T[j,i]，这才是有效转置；只改 shape 标签会被数值测试抓住。",
      visual: ["A[0,2] = 7", "A^T[2,0] = 7", "shape ok + index ok"]
    },
    {
      title: "QK^T 的那个 T",
      body: "Q 和 K 的最后一轴 D 是 feature width。QK^T 要把 K 的 token 轴变成列，让输出成为 query-token by key-token 的 T x T 分数板。",
      visual: ["Q[B,H,T,D]", "K[B,H,T,D] -> K^T[B,H,D,T]", "scores[B,H,T,T]"]
    }
  ],
  knowledgeTransition: {
    title: "QK^T Repair Bootcamp",
    body: "进入画布后，从 0-3A 开始。\n\n每个阶段只增加一个新陷阱：先看二维索引，再看 MatMul 内维度，再看多头 attention 的携带轴。",
    buttonLabel: "Start Transpose Trap"
  },
  mission: {
    title: "Repair Mission: Transpose Trap Ladder",
    body: "当前训练板会按 0-3A 到 0-3X 逐步打开。你需要证明自己理解了 transpose 的 shape、axis semantics 和 numeric mapping，而不是只记住一个形状。",
    success: [
      "0-3A 到 0-3E 每个阶段都在画布上完成槽位修复。",
      "0-3F 能识别转置 Q、转错轴、操作数顺序反了、shape 过但数值错等故障。",
      "0-3X 隐藏测试包含 T==D 和 carry axes 变体。"
    ]
  },
  unlocks: ["Transpose Switch", "QK Score Board", "Axis Contract Debugger", "Attention Preview"],
  contracts: [
    "2D: A[R,C] -> A^T[C,R] and A[i,j] = A^T[j,i]",
    "MatMul repair: A[M,N] @ B^T[N,P] -> out[M,P]",
    "Higher-rank: swap only the last two axes, keep carry axes fixed",
    "Attention: Q[B,H,T,D] @ K^T[B,H,D,T] -> scores[B,H,T,T]"
  ],
  nodes: [
    makeNode({
      id: "matrix_plate",
      title: "Matrix Plate",
      subtitle: "rows x columns",
      kind: "matrix",
      semanticName: "A",
      dtype: "float32",
      shape: "[R,C]",
      source: "visible fixture",
      consumer: "transpose_2d",
      stats: { min: "1", max: "6", mean: "3.5" },
      sample: ["A = [[1,2,3],[4,5,6]]", "R=2, C=3"],
      checks: [check("matrix axes", "warn", "identify rows and columns before flipping")],
      x: 76,
      y: 182,
      w: 210,
      h: 126,
      color: 0x24608a
    }),
    makeNode({
      id: "transpose_2d",
      title: "Transpose Switch",
      subtitle: "2D switch off",
      kind: "operation",
      semanticName: "transpose",
      dtype: "op",
      shape: "[R,C] -> ?",
      source: "matrix plate",
      consumer: "matrix_t_plate",
      sample: ["target: swap row and column axes", "A[i,j] must move to A^T[j,i]"],
      checks: [check("switch", "warn", "configure transpose instead of relabeling")],
      x: 396,
      y: 196,
      w: 220,
      h: 98,
      color: 0x304b6a
    }),
    makeNode({
      id: "matrix_t_plate",
      title: "Flipped Matrix",
      subtitle: "waiting for values",
      kind: "matrix",
      semanticName: "A_T",
      dtype: "float32",
      shape: "[?,?]",
      source: "transpose_2d",
      consumer: "index_checker",
      stats: { min: "1", max: "6", mean: "3.5" },
      sample: ["target: [[1,4],[2,5],[3,6]]", "A^T[2,0] should equal A[0,2]"],
      checks: [check("index mapping", "warn", "shape and values must both match")],
      x: 736,
      y: 174,
      w: 238,
      h: 138,
      color: 0x24608a
    }),
    makeNode({
      id: "index_checker",
      title: "Index Checker",
      subtitle: "A[i,j] -> A^T[j,i]",
      kind: "scalar",
      semanticName: "index_test",
      dtype: "bool",
      shape: "all cells",
      source: "matrix_t_plate",
      consumer: "stage gate",
      sample: ["A[0,2] == A^T[2,0]", "A[1,0] == A^T[0,1]"],
      checks: [check("numeric mapping", "warn", "not just a shape label test")],
      x: 1040,
      y: 196,
      w: 190,
      h: 98,
      color: 0x74491a
    }),
    makeNode({
      id: "matmul_a",
      title: "A Matrix",
      subtitle: "left operand",
      kind: "matrix",
      semanticName: "A",
      dtype: "float32",
      shape: "[M,N]",
      source: "fixture A",
      consumer: "matmul_repair_gate.left",
      stats: { min: "-1.2", max: "1.4", mean: "0.04" },
      sample: ["A: [2,3]", "left inner axis is N"],
      checks: [check("left operand", "pass", "A exposes N on its last axis")],
      x: 74,
      y: 156,
      w: 202,
      h: 118,
      color: 0x24608a
    }),
    makeNode({
      id: "matmul_b_bad",
      title: "B Matrix",
      subtitle: "stored wrong way",
      kind: "matrix",
      semanticName: "B_stored",
      dtype: "float32",
      shape: "[P,N]",
      source: "fixture B",
      consumer: "transpose_b_repair",
      stats: { min: "-0.8", max: "1.1", mean: "0.02" },
      sample: ["B stored: [4,3]", "gate needs [N,P]"],
      checks: [check("orientation", "warn", "right operand is not compute-ready")],
      x: 74,
      y: 364,
      w: 202,
      h: 118,
      color: 0x5a4c8f
    }),
    makeNode({
      id: "transpose_b_repair",
      title: "Transpose B",
      subtitle: "repair inner dim",
      kind: "operation",
      semanticName: "transpose_B",
      dtype: "op",
      shape: "[P,N] -> ?",
      source: "B_stored",
      consumer: "matmul_repair_gate.right",
      sample: ["B^T: [N,P]", "N must meet N"],
      checks: [check("repair", "warn", "insert transpose on B, not A")],
      x: 370,
      y: 374,
      w: 218,
      h: 96,
      color: 0x304b6a
    }),
    makeNode({
      id: "matmul_repair_gate",
      title: "MatMul Gate",
      subtitle: "inner dim blocked",
      kind: "operation",
      semanticName: "matmul",
      dtype: "op",
      shape: "[M,N]@[?,?]",
      source: "A, B path",
      consumer: "matmul_repair_out",
      sample: ["target: [M,N] @ [N,P]", "output: [M,P]"],
      checks: [check("inner dims", "warn", "N must align with N")],
      x: 668,
      y: 252,
      w: 210,
      h: 104,
      color: 0x304b6a
    }),
    makeNode({
      id: "matmul_repair_out",
      title: "MatMul Output",
      subtitle: "waiting for reference",
      kind: "matrix",
      semanticName: "out",
      dtype: "float32",
      shape: "[?,?]",
      source: "matmul_repair_gate",
      consumer: "reference_checker_03",
      stats: { min: "-1.9", max: "2.0", mean: "0.01" },
      sample: ["expected shape: [M,P]", "numeric close to A @ B.T"],
      checks: [check("output", "warn", "shape and numeric output must pass")],
      x: 968,
      y: 234,
      w: 226,
      h: 122,
      color: 0x24608a
    }),
    makeNode({
      id: "reference_checker_03",
      title: "Reference Checker",
      subtitle: "allclose gate",
      kind: "scalar",
      semanticName: "max_error",
      dtype: "float32",
      shape: "<= 1e-5",
      source: "matmul output",
      consumer: "stage gate",
      sample: ["shape can pass while values fail", "compare against A @ B.transpose(-2,-1)"],
      checks: [check("numeric", "warn", "reference allclose required")],
      x: 968,
      y: 408,
      w: 226,
      h: 100,
      color: 0x74491a
    }),
    makeNode({
      id: "rank3_tensor",
      title: "Rank-3 Tensor",
      subtitle: "K[B,T,D]",
      kind: "tensor",
      semanticName: "K3",
      dtype: "float32",
      shape: "[B,T,D]",
      source: "single-head key table",
      consumer: "axis_swap_switch",
      stats: { min: "-1.0", max: "1.0", mean: "0.00" },
      sample: ["target after swap: [B,D,T]", "B is a carry axis"],
      checks: [check("carry axis", "warn", "B must not move")],
      x: 78,
      y: 152,
      w: 224,
      h: 122,
      color: 0x24608a
    }),
    makeNode({
      id: "rank4_tensor",
      title: "Rank-4 Tensor",
      subtitle: "K[B,H,T,D]",
      kind: "tensor",
      semanticName: "K4",
      dtype: "float32",
      shape: "[B,H,T,D]",
      source: "multi-head key table",
      consumer: "axis_swap_switch",
      stats: { min: "-1.1", max: "1.2", mean: "0.01" },
      sample: ["target after swap: [B,H,D,T]", "B/H are carry axes"],
      checks: [check("carry axes", "warn", "B and H must remain in place")],
      x: 78,
      y: 350,
      w: 224,
      h: 122,
      color: 0x24608a
    }),
    makeNode({
      id: "axis_swap_switch",
      title: "Axis Swap Switch",
      subtitle: "swap(-2,-1) not set",
      kind: "operation",
      semanticName: "swap_axes",
      dtype: "op",
      shape: "last-two axes",
      source: "rank3/rank4 tensors",
      consumer: "carry_axis_lock",
      sample: ["swap(-2,-1) means T <-> D", "full reverse is wrong"],
      checks: [check("axis config", "warn", "only the last two axes should swap")],
      x: 412,
      y: 254,
      w: 238,
      h: 110,
      color: 0x304b6a
    }),
    makeNode({
      id: "carry_axis_lock",
      title: "Axis Lock",
      subtitle: "carry axes protected",
      kind: "operation",
      semanticName: "axis_contract",
      dtype: "rule",
      shape: "keep prefix axes",
      source: "axis swap switch",
      consumer: "higher_rank_checker",
      sample: ["B/H are parallel layers", "transpose trap only touches T/D"],
      checks: [check("prefix axes", "warn", "protect carry axes from permutation")],
      x: 734,
      y: 254,
      w: 226,
      h: 110,
      color: 0x304b6a
    }),
    makeNode({
      id: "higher_rank_checker",
      title: "Higher-Rank Checker",
      subtitle: "rank 3 + rank 4",
      kind: "scalar",
      semanticName: "axis_tests",
      dtype: "bool",
      shape: "2 cases",
      source: "axis lock",
      consumer: "stage gate",
      sample: ["[B,T,D] -> [B,D,T]", "[B,H,T,D] -> [B,H,D,T]"],
      checks: [check("axis semantics", "warn", "carry axes preserved, T/D swapped")],
      x: 1030,
      y: 258,
      w: 218,
      h: 104,
      color: 0x74491a
    }),
    makeNode({
      id: "q_single",
      title: "Q Tensor",
      subtitle: "single head",
      kind: "tensor",
      semanticName: "Q",
      dtype: "float32",
      shape: "[T,D]",
      source: "query projection",
      consumer: "single_qk_matmul.left",
      stats: { min: "-1.2", max: "1.1", mean: "-0.02" },
      sample: ["T query rows", "D feature columns"],
      checks: [check("query", "pass", "query token rows stay on the left")],
      x: 78,
      y: 160,
      w: 214,
      h: 116,
      color: 0x24608a
    }),
    makeNode({
      id: "k_single",
      title: "K Tensor",
      subtitle: "single head",
      kind: "tensor",
      semanticName: "K",
      dtype: "float32",
      shape: "[T,D]",
      source: "key projection",
      consumer: "k_single_transpose",
      stats: { min: "-1.3", max: "1.4", mean: "0.01" },
      sample: ["raw K has token rows", "right operand must become [D,T]"],
      checks: [check("key", "warn", "K needs transpose before QK")],
      x: 78,
      y: 360,
      w: 214,
      h: 116,
      color: 0x24608a
    }),
    makeNode({
      id: "k_single_transpose",
      title: "K^T Switch",
      subtitle: "not configured",
      kind: "operation",
      semanticName: "transpose_K",
      dtype: "op",
      shape: "[T,D] -> ?",
      source: "K",
      consumer: "single_qk_matmul.right",
      sample: ["target: [D,T]", "key token axis becomes columns"],
      checks: [check("transpose", "warn", "transpose K, not Q")],
      x: 390,
      y: 374,
      w: 218,
      h: 96,
      color: 0x304b6a
    }),
    makeNode({
      id: "single_qk_matmul",
      title: "QK MatMul",
      subtitle: "blocked",
      kind: "operation",
      semanticName: "qk_scores",
      dtype: "op",
      shape: "[T,D]@[?,?]",
      source: "Q, K path",
      consumer: "single_scores",
      sample: ["target: [T,D] @ [D,T]", "out: [T,T]"],
      checks: [check("inner dims", "warn", "D must meet D")],
      x: 668,
      y: 254,
      w: 210,
      h: 104,
      color: 0x304b6a
    }),
    makeNode({
      id: "single_scores",
      title: "Score Board",
      subtitle: "token x token",
      kind: "attention",
      semanticName: "scores",
      dtype: "float32",
      shape: "[?,?]",
      source: "Q @ K^T",
      consumer: "attention preview",
      stats: { min: "-2.0", max: "2.2", mean: "0.03" },
      sample: ["rows: query token", "columns: key token"],
      checks: [check("score shape", "warn", "single-head scores must be [T,T]")],
      x: 964,
      y: 232,
      w: 238,
      h: 132,
      color: 0x1b6f78
    }),
    makeNode({
      id: "q_heads",
      title: "Q Tensor",
      subtitle: "multi-head",
      kind: "tensor",
      semanticName: "Q",
      dtype: "float32",
      shape: "[B,H,T,D]",
      source: "split heads",
      consumer: "multi_qk_matmul.left",
      stats: { min: "-1.6", max: "1.4", mean: "-0.02" },
      sample: ["visible: [1,2,4,3]", "B/H are parallel layers"],
      checks: [check("left shape", "pass", "[B,H,T,D]")],
      x: 74,
      y: 148,
      w: 220,
      h: 124,
      color: 0x24608a
    }),
    makeNode({
      id: "k_heads",
      title: "K Tensor",
      subtitle: "multi-head",
      kind: "tensor",
      semanticName: "K",
      dtype: "float32",
      shape: "[B,H,T,D]",
      source: "split heads",
      consumer: "k_heads_transpose",
      stats: { min: "-1.5", max: "1.7", mean: "0.01" },
      sample: ["raw K matches Q shape", "right operand must become [B,H,D,T]"],
      checks: [check("trap", "warn", "raw K has last dims T,D")],
      x: 74,
      y: 360,
      w: 220,
      h: 124,
      color: 0x24608a
    }),
    makeNode({
      id: "k_heads_transpose",
      title: "K^T Switch",
      subtitle: "not configured",
      kind: "operation",
      semanticName: "transpose_K_heads",
      dtype: "op",
      shape: "off",
      source: "K[B,H,T,D]",
      consumer: "multi_qk_matmul.right",
      sample: ["target: K^T[B,H,D,T]", "B/H must stay fixed"],
      checks: [check("required", "warn", "set swap(-2,-1) on K path")],
      x: 392,
      y: 374,
      w: 230,
      h: 98,
      color: 0x304b6a
    }),
    makeNode({
      id: "multi_qk_matmul",
      title: "QK MatMul",
      subtitle: "blocked",
      kind: "operation",
      semanticName: "qk_scores",
      dtype: "op",
      shape: "[T,D]@[?,?]",
      source: "Q, K path",
      consumer: "multi_scores",
      sample: ["per B/H: [T,D] @ [D,T]", "out: [B,H,T,T]"],
      checks: [check("inner dims", "warn", "D must align within every head")],
      x: 682,
      y: 254,
      w: 212,
      h: 104,
      color: 0x304b6a
    }),
    makeNode({
      id: "multi_scores",
      title: "Scores",
      subtitle: "attention board stack",
      kind: "attention",
      semanticName: "scores",
      dtype: "float32",
      shape: "[B,H,?,?]",
      source: "Q @ K path",
      consumer: "mask + softmax",
      stats: { min: "-2.4", max: "2.1", mean: "-0.03" },
      sample: ["target: square T x T board", "visible: [1,2,4,4]"],
      checks: [check("target", "warn", "must match [B,H,T,T]")],
      x: 968,
      y: 218,
      w: 238,
      h: 142,
      color: 0x1b6f78
    }),
    makeNode({
      id: "faulty_board",
      title: "Faulty Board",
      subtitle: "mixed bugs",
      kind: "attention",
      semanticName: "qk_fault",
      dtype: "debug",
      shape: "varies",
      source: "saved player circuits",
      consumer: "trace_inspector",
      sample: ["Case 1: Q^T @ K", "Case 2: Q @ K when T==D", "Case 3: swapped B/H"],
      checks: [check("fault set", "warn", "debug more than one trap type")],
      x: 84,
      y: 214,
      w: 232,
      h: 136,
      color: 0x74491a
    }),
    makeNode({
      id: "trace_inspector",
      title: "Trace Inspector",
      subtitle: "axis contract first",
      kind: "operation",
      semanticName: "trace",
      dtype: "tool",
      shape: "Q/K/scores",
      source: "faulty board",
      consumer: "cell_source_checker",
      sample: ["inspect operand order", "inspect last two axes", "inspect cell source"],
      checks: [check("trace", "warn", "diagnose before patching")],
      x: 400,
      y: 228,
      w: 232,
      h: 112,
      color: 0x304b6a
    }),
    makeNode({
      id: "cell_source_checker",
      title: "Cell Source Checker",
      subtitle: "scores[tq,tk]",
      kind: "operation",
      semanticName: "cell_trace",
      dtype: "tool",
      shape: "cell provenance",
      source: "trace inspector",
      consumer: "trap_patch",
      sample: ["scores[2,1] = q_2 dot k_1", "not q_1 dot k_2"],
      checks: [check("numeric trap", "warn", "shape can pass while source is wrong")],
      x: 704,
      y: 228,
      w: 238,
      h: 112,
      color: 0x304b6a
    }),
    makeNode({
      id: "trap_patch",
      title: "Repair Patch",
      subtitle: "waiting",
      kind: "operation",
      semanticName: "patch",
      dtype: "rule",
      shape: "3 fixes",
      source: "cell source checker",
      consumer: "trap_reference",
      sample: ["fix operand order", "add K^T", "preserve carry axes"],
      checks: [check("patch", "warn", "record all three repair rules")],
      x: 1002,
      y: 228,
      w: 224,
      h: 112,
      color: 0x304b6a
    }),
    makeNode({
      id: "trap_reference",
      title: "Reference Checker",
      subtitle: "debug allclose",
      kind: "scalar",
      semanticName: "debug_reference",
      dtype: "float32",
      shape: "<= 1e-5",
      source: "repair patch",
      consumer: "gauntlet",
      sample: ["shape ok is not enough", "T==D case forces numeric check"],
      checks: [check("allclose", "warn", "patched circuits must match reference")],
      x: 1002,
      y: 402,
      w: 224,
      h: 100,
      color: 0x74491a
    }),
    makeNode({
      id: "gauntlet_cases",
      title: "Gauntlet Cases",
      subtitle: "hidden QK boards",
      kind: "source",
      semanticName: "qk_cases",
      dtype: "fixtures",
      shape: "4 cases",
      source: "hidden tests",
      consumer: "qk_contract_terminal",
      sample: ["A: standard", "B: carry axes moved", "C: T==D numeric trap", "D: reversed operands"],
      checks: [check("cases", "warn", "arm all hidden cases")],
      x: 100,
      y: 228,
      w: 238,
      h: 132,
      color: 0x1a4164
    }),
    makeNode({
      id: "qk_contract_terminal",
      title: "QK^T Contract",
      subtitle: "general rule",
      kind: "operation",
      semanticName: "qk_contract",
      dtype: "rule",
      shape: "Q[...,T,D] @ K[...,D,T]",
      source: "gauntlet cases",
      consumer: "hidden_reference",
      sample: ["prefix axes are carried", "last two axes do the matmul"],
      checks: [check("contract", "warn", "apply semantic rule, not memorized sizes")],
      x: 440,
      y: 236,
      w: 268,
      h: 116,
      color: 0x304b6a
    }),
    makeNode({
      id: "hidden_reference",
      title: "Hidden Reference",
      subtitle: "allclose + shape",
      kind: "scalar",
      semanticName: "hidden_reference",
      dtype: "bool",
      shape: "shape + numeric",
      source: "qk contract",
      consumer: "gauntlet_result",
      sample: ["case C: T == D", "numeric provenance decides correctness"],
      checks: [check("reference", "warn", "hidden cases include shape-equal traps")],
      x: 792,
      y: 236,
      w: 238,
      h: 116,
      color: 0x74491a
    }),
    makeNode({
      id: "gauntlet_result",
      title: "Transpose Gauntlet",
      subtitle: "run final tests",
      kind: "scalar",
      semanticName: "gauntlet",
      dtype: "bool",
      shape: "4/4",
      source: "hidden reference",
      consumer: "chapter unlock",
      sample: ["standard non-equal sizes", "carry axes preserved", "T==D numeric trap", "operand order trap"],
      checks: [check("hidden tests", "warn", "prove the transpose contract generalizes")],
      x: 1100,
      y: 236,
      w: 226,
      h: 116,
      color: 0x74491a
    })
  ],
  edges: [
    { id: "e_03a_matrix_switch", from: "matrix_plate", to: "transpose_2d", label: "A[R,C]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03a_switch_out", from: "transpose_2d", to: "matrix_t_plate", label: "A^T[C,R]", color: 0x22c55e, flow: "forward" },
    { id: "e_03a_out_index", from: "matrix_t_plate", to: "index_checker", label: "index map", color: 0xfbbf24, flow: "check" },
    { id: "e_03b_a_matmul", from: "matmul_a", to: "matmul_repair_gate", label: "A[M,N]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03b_b_transpose", from: "matmul_b_bad", to: "transpose_b_repair", label: "B[P,N]", color: 0xfbbf24, flow: "parameter" },
    { id: "e_03b_transpose_matmul", from: "transpose_b_repair", to: "matmul_repair_gate", label: "B^T[N,P]", color: 0xfbbf24, flow: "parameter" },
    { id: "e_03b_matmul_out", from: "matmul_repair_gate", to: "matmul_repair_out", label: "out[M,P]", color: 0x22c55e, flow: "forward" },
    { id: "e_03b_out_ref", from: "matmul_repair_out", to: "reference_checker_03", label: "allclose", color: 0x22c55e, flow: "check", route: "down" },
    { id: "e_03c_rank3_switch", from: "rank3_tensor", to: "axis_swap_switch", label: "K[B,T,D]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03c_rank4_switch", from: "rank4_tensor", to: "axis_swap_switch", label: "K[B,H,T,D]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03c_switch_lock", from: "axis_swap_switch", to: "carry_axis_lock", label: "swap(-2,-1)", color: 0xfbbf24, flow: "check" },
    { id: "e_03c_lock_checker", from: "carry_axis_lock", to: "higher_rank_checker", label: "preserve prefix", color: 0x22c55e, flow: "check" },
    { id: "e_03d_q_matmul", from: "q_single", to: "single_qk_matmul", label: "Q[T,D]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03d_k_transpose", from: "k_single", to: "k_single_transpose", label: "K[T,D]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03d_transpose_matmul", from: "k_single_transpose", to: "single_qk_matmul", label: "K^T[D,T]", color: 0xfbbf24, flow: "parameter" },
    { id: "e_03d_matmul_scores", from: "single_qk_matmul", to: "single_scores", label: "scores[T,T]", color: 0x22c55e, flow: "forward" },
    { id: "e_03e_q_matmul", from: "q_heads", to: "multi_qk_matmul", label: "Q[B,H,T,D]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03e_k_transpose", from: "k_heads", to: "k_heads_transpose", label: "K[B,H,T,D]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03e_transpose_matmul", from: "k_heads_transpose", to: "multi_qk_matmul", label: "K^T[B,H,D,T]", color: 0xfbbf24, flow: "parameter" },
    { id: "e_03e_matmul_scores", from: "multi_qk_matmul", to: "multi_scores", label: "scores[B,H,T,T]", color: 0x22c55e, flow: "forward" },
    { id: "e_03f_fault_trace", from: "faulty_board", to: "trace_inspector", label: "fault trace", color: 0xfbbf24, flow: "check" },
    { id: "e_03f_trace_cell", from: "trace_inspector", to: "cell_source_checker", label: "cell provenance", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03f_cell_patch", from: "cell_source_checker", to: "trap_patch", label: "repair rules", color: 0x22c55e, flow: "check" },
    { id: "e_03f_patch_ref", from: "trap_patch", to: "trap_reference", label: "allclose", color: 0x22c55e, flow: "check", route: "down" },
    { id: "e_03x_cases_contract", from: "gauntlet_cases", to: "qk_contract_terminal", label: "random fixtures", color: 0x7dd3fc, flow: "forward" },
    { id: "e_03x_contract_ref", from: "qk_contract_terminal", to: "hidden_reference", label: "shape + numeric", color: 0xfbbf24, flow: "check" },
    { id: "e_03x_ref_result", from: "hidden_reference", to: "gauntlet_result", label: "hidden pass", color: 0x22c55e, flow: "check" }
  ],
  repair: {
    kind: "transpose_switch",
    targetContract: "Q[B,H,T,D] @ K^T[B,H,D,T] -> scores[B,H,T,T]",
    brokenMessage: "Transpose Trap incomplete: shape, axis semantics, numeric mapping, QK^T score board, and hidden T==D tests must all pass.",
    budget: { probes: 9, referenceRuns: 5 },
    tags: [
      { id: "op_transpose_2d", label: "2D Transpose", shortLabel: "T", detail: "swap matrix row and column axes", category: "operation" },
      { id: "op_relabel_only", label: "Relabel Only", shortLabel: "label", detail: "wrong: changes labels without moving values", category: "operation" },
      { id: "shape_cr", label: "Output Shape [C,R]", shortLabel: "[C,R]", detail: "matrix transpose output shape", category: "contract" },
      { id: "shape_rc", label: "Output Shape [R,C]", shortLabel: "[R,C]", detail: "wrong: leaves matrix orientation unchanged", category: "contract" },
      { id: "index_mirror", label: "Index Mirror", shortLabel: "i,j->j,i", detail: "A[i,j] equals A^T[j,i]", category: "contract" },
      { id: "index_shuffle", label: "Random Shuffle", shortLabel: "shuffle", detail: "wrong: values are not randomly reordered", category: "contract" },
      { id: "b_orientation_fault", label: "B stored as [P,N]", shortLabel: "B[P,N]", detail: "right operand is stored in the wrong compute direction", category: "contract" },
      { id: "a_orientation_fault", label: "A is wrong", shortLabel: "A bad", detail: "wrong: A already exposes N as inner axis", category: "contract" },
      { id: "transpose_b", label: "Transpose B", shortLabel: "T(B)", detail: "turn B[P,N] into B^T[N,P]", category: "operation" },
      { id: "transpose_a", label: "Transpose A", shortLabel: "T(A)", detail: "wrong: transposing A breaks the left operand", category: "operation" },
      { id: "shape_mp", label: "Output [M,P]", shortLabel: "[M,P]", detail: "repaired matmul output contract", category: "contract" },
      { id: "shape_np", label: "Output [N,P]", shortLabel: "[N,P]", detail: "wrong: N is consumed, not preserved", category: "contract" },
      { id: "reference_allclose_03b", label: "Reference Allclose", shortLabel: "allclose", detail: "numeric output matches A @ B.T", category: "contract" },
      { id: "swap_last_two", label: "swap(-2,-1)", shortLabel: "-2<->-1", detail: "swap only the last two axes", category: "operation" },
      { id: "reverse_all_axes", label: "Reverse All Axes", shortLabel: "reverse", detail: "wrong: turns [B,H,T,D] into [D,T,H,B]", category: "operation" },
      { id: "preserve_b_03c", label: "Preserve B", shortLabel: "keep B", detail: "rank-3 carry axis remains fixed", category: "axis" },
      { id: "preserve_bh_03c", label: "Preserve B/H", shortLabel: "keep B/H", detail: "rank-4 carry axes remain fixed", category: "axis" },
      { id: "swap_ht_wrong", label: "Swap H and T", shortLabel: "H<->T", detail: "wrong: breaks head layers", category: "axis" },
      { id: "not_full_reverse", label: "Not Full Reverse", shortLabel: "no reverse", detail: "transpose trap is not all-axis reversal", category: "contract" },
      { id: "transpose_k_single", label: "Transpose K", shortLabel: "K^T", detail: "single-head K[T,D] becomes K^T[D,T]", category: "operation" },
      { id: "transpose_q_single", label: "Transpose Q", shortLabel: "Q^T", detail: "wrong: query rows should remain output rows", category: "operation" },
      { id: "scores_tt_single", label: "Scores [T,T]", shortLabel: "[T,T]", detail: "single-head token-to-token score board", category: "contract" },
      { id: "scores_dd_single", label: "Scores [D,D]", shortLabel: "[D,D]", detail: "wrong: feature-to-feature board", category: "contract" },
      { id: "query_key_axes", label: "Rows=query, cols=key", shortLabel: "q rows/k cols", detail: "score cell is q_t dot k_s", category: "axis" },
      { id: "feature_feature_axes", label: "Feature by Feature", shortLabel: "D by D", detail: "wrong: scores should compare tokens", category: "axis" },
      { id: "transpose_k_multi", label: "Transpose K last axes", shortLabel: "K^T last", detail: "K[B,H,T,D] -> K^T[B,H,D,T]", category: "operation" },
      { id: "transpose_q_multi", label: "Transpose Q last axes", shortLabel: "Q^T last", detail: "wrong: Q token rows must stay rows", category: "operation" },
      { id: "preserve_bh_03e", label: "Preserve B/H", shortLabel: "keep B/H", detail: "batch and head axes are parallel carry axes", category: "axis" },
      { id: "move_bh_wrong", label: "Move B/H", shortLabel: "move B/H", detail: "wrong: B/H are not part of the score matrix", category: "axis" },
      { id: "scores_bhtt", label: "Scores [B,H,T,T]", shortLabel: "[B,H,T,T]", detail: "multi-head attention score stack", category: "contract" },
      { id: "scores_bhdd", label: "Scores [B,H,D,D]", shortLabel: "[B,H,D,D]", detail: "wrong: feature board instead of token board", category: "contract" },
      { id: "debug_operand_order", label: "Check Operand Order", shortLabel: "Q left/K right", detail: "Q must stay left, K^T must be right", category: "operation" },
      { id: "debug_shape_only", label: "Trust Shape Only", shortLabel: "shape only", detail: "wrong: T==D can hide numeric bugs", category: "operation" },
      { id: "debug_numeric_cell", label: "Trace One Cell", shortLabel: "cell trace", detail: "scores[tq,tk] must come from q_t dot k_tk", category: "operation" },
      { id: "debug_axis_contract", label: "Inspect Axis Contract", shortLabel: "axis first", detail: "inspect semantic axes before trusting sizes", category: "axis" },
      { id: "debug_patch_rules", label: "Patch All Faults", shortLabel: "3 fixes", detail: "repair operand order, K transpose, and carry axes", category: "contract" },
      { id: "case_standard", label: "Case A Standard", shortLabel: "A std", detail: "non-equal T/D standard QK^T", category: "contract" },
      { id: "case_carry_axes", label: "Case B Carry Axes", shortLabel: "B carry", detail: "B/H sizes vary but must stay fixed", category: "contract" },
      { id: "case_td_equal", label: "Case C T==D", shortLabel: "C T==D", detail: "shape can pass while numeric mapping fails", category: "contract" },
      { id: "case_operand_order", label: "Case D Operand Order", shortLabel: "D order", detail: "reject K @ Q^T or swapped score semantics", category: "contract" }
    ],
    slots: [
      {
        id: "matrix_flip_switch",
        label: "2D Switch",
        nodeId: "transpose_2d",
        focusNodeId: "transpose_2d",
        emptyLabel: "?",
        correctTagIds: ["op_transpose_2d"],
        expected: "use a real 2D transpose",
        successDetail: "Matrix row and column axes are actually swapped.",
        failureDetail: "Transpose must move values; relabeling or shuffling is not enough."
      },
      {
        id: "matrix_flip_shape",
        label: "Flipped Shape",
        nodeId: "matrix_t_plate",
        focusNodeId: "matrix_t_plate",
        emptyLabel: "?",
        correctTagIds: ["shape_cr"],
        expected: "A^T shape is [C,R]",
        successDetail: "Output matrix has columns by rows.",
        failureDetail: "A transposed [R,C] matrix should become [C,R]."
      },
      {
        id: "matrix_flip_index",
        label: "Index Mapping",
        nodeId: "index_checker",
        focusNodeId: "index_checker",
        emptyLabel: "?",
        correctTagIds: ["index_mirror"],
        expected: "A[i,j] == A^T[j,i]",
        successDetail: "Index mapping proves values moved correctly.",
        failureDetail: "Shape passing is not enough; each value must move to its mirrored coordinate."
      },
      {
        id: "inner_dim_fault",
        label: "Fault Source",
        nodeId: "matmul_b_bad",
        focusNodeId: "matmul_b_bad",
        emptyLabel: "?",
        correctTagIds: ["b_orientation_fault"],
        expected: "B is stored as [P,N]",
        successDetail: "The right operand has the wrong compute orientation.",
        failureDetail: "A already has [M,N]; the fault is B's orientation."
      },
      {
        id: "inner_dim_fix",
        label: "Repair Operation",
        nodeId: "transpose_b_repair",
        focusNodeId: "transpose_b_repair",
        emptyLabel: "?",
        correctTagIds: ["transpose_b"],
        expected: "transpose B into [N,P]",
        successDetail: "B^T exposes N for MatMul's inner dimension.",
        failureDetail: "This repair should transpose B, not A."
      },
      {
        id: "inner_dim_output",
        label: "Output Contract",
        nodeId: "matmul_repair_out",
        focusNodeId: "matmul_repair_out",
        emptyLabel: "?",
        correctTagIds: ["shape_mp"],
        expected: "out shape is [M,P]",
        successDetail: "N is consumed and P becomes the output width.",
        failureDetail: "N should disappear from the output; the correct output is [M,P]."
      },
      {
        id: "inner_dim_numeric",
        label: "Numeric Reference",
        nodeId: "reference_checker_03",
        focusNodeId: "reference_checker_03",
        emptyLabel: "?",
        correctTagIds: ["reference_allclose_03b"],
        expected: "output allclose to A @ B.T",
        successDetail: "Repaired MatMul matches the reference numerically.",
        failureDetail: "A shape-only repair can still put values in the wrong cells."
      },
      {
        id: "rank3_swap_axes",
        label: "Rank-3 Swap",
        nodeId: "axis_swap_switch",
        focusNodeId: "rank3_tensor",
        emptyLabel: "?",
        correctTagIds: ["swap_last_two"],
        expected: "[B,T,D] -> [B,D,T]",
        successDetail: "Rank-3 tensor swaps only T and D.",
        failureDetail: "Rank-3 transpose should not move the carry B axis."
      },
      {
        id: "rank3_carry_axis",
        label: "Rank-3 Carry",
        nodeId: "carry_axis_lock",
        focusNodeId: "rank3_tensor",
        emptyLabel: "?",
        correctTagIds: ["preserve_b_03c"],
        expected: "B axis preserved",
        successDetail: "B remains a prefix carry axis.",
        failureDetail: "B separates samples and should not be part of the last-two-axis swap."
      },
      {
        id: "rank4_carry_axes",
        label: "Rank-4 Carry",
        nodeId: "carry_axis_lock",
        focusNodeId: "rank4_tensor",
        emptyLabel: "?",
        correctTagIds: ["preserve_bh_03c"],
        expected: "B/H axes preserved",
        successDetail: "Batch and head axes remain parallel layers.",
        failureDetail: "Do not swap H with T or reverse all axes."
      },
      {
        id: "no_full_reverse",
        label: "No Full Reverse",
        nodeId: "higher_rank_checker",
        focusNodeId: "higher_rank_checker",
        emptyLabel: "?",
        correctTagIds: ["not_full_reverse"],
        expected: "transpose trap is not all-axis reversal",
        successDetail: "The repair rejects full axis reversal.",
        failureDetail: "QK^T uses swap(-2,-1), not reverse()."
      },
      {
        id: "single_k_transpose",
        label: "K Path",
        nodeId: "k_single_transpose",
        focusNodeId: "k_single_transpose",
        emptyLabel: "?",
        correctTagIds: ["transpose_k_single"],
        expected: "K[T,D] -> K^T[D,T]",
        successDetail: "K is transposed for single-head QK.",
        failureDetail: "Transpose K, not Q."
      },
      {
        id: "single_score_shape",
        label: "Score Shape",
        nodeId: "single_scores",
        focusNodeId: "single_scores",
        emptyLabel: "?",
        correctTagIds: ["scores_tt_single"],
        expected: "scores shape is [T,T]",
        successDetail: "Single-head scores are square over token positions.",
        failureDetail: "The score board should compare tokens, not features."
      },
      {
        id: "single_score_semantics",
        label: "Score Semantics",
        nodeId: "single_scores",
        focusNodeId: "single_scores",
        emptyLabel: "?",
        correctTagIds: ["query_key_axes"],
        expected: "rows are query tokens, columns are key tokens",
        successDetail: "Each score cell means q_t dot k_s.",
        failureDetail: "The two T axes are not arbitrary; row and column roles matter."
      },
      {
        id: "multi_k_transpose",
        label: "K Path",
        nodeId: "k_heads_transpose",
        focusNodeId: "k_heads_transpose",
        emptyLabel: "?",
        correctTagIds: ["transpose_k_multi"],
        expected: "K[B,H,T,D] -> K^T[B,H,D,T]",
        successDetail: "K path swaps only the last two axes.",
        failureDetail: "K must be transposed before the multi-head QK MatMul."
      },
      {
        id: "multi_carry_axes",
        label: "Carry Axes",
        nodeId: "k_heads_transpose",
        focusNodeId: "k_heads_transpose",
        emptyLabel: "?",
        correctTagIds: ["preserve_bh_03e"],
        expected: "B/H stay fixed",
        successDetail: "Batch and head axes are preserved.",
        failureDetail: "B/H are parallel layers and must not enter the score board."
      },
      {
        id: "multi_score_shape",
        label: "Score Stack",
        nodeId: "multi_scores",
        focusNodeId: "multi_scores",
        emptyLabel: "?",
        correctTagIds: ["scores_bhtt"],
        expected: "scores shape is [B,H,T,T]",
        successDetail: "Every batch/head layer receives a T x T score board.",
        failureDetail: "The output must be [B,H,T,T], not [B,H,D,D] or reordered axes."
      },
      {
        id: "debug_operand_order",
        label: "Operand Order",
        nodeId: "trace_inspector",
        focusNodeId: "trace_inspector",
        emptyLabel: "?",
        correctTagIds: ["debug_operand_order"],
        expected: "Q left, K^T right",
        successDetail: "The debugger checks operand order first.",
        failureDetail: "Swapped operands can produce plausible shapes but reversed score semantics."
      },
      {
        id: "debug_numeric_trap",
        label: "Numeric Trap",
        nodeId: "cell_source_checker",
        focusNodeId: "cell_source_checker",
        emptyLabel: "?",
        correctTagIds: ["debug_numeric_cell"],
        expected: "trace a single score cell",
        successDetail: "Cell provenance catches T==D shape traps.",
        failureDetail: "Do not trust shape alone when T and D are equal."
      },
      {
        id: "debug_axis_contract",
        label: "Axis Contract",
        nodeId: "trace_inspector",
        focusNodeId: "trace_inspector",
        emptyLabel: "?",
        correctTagIds: ["debug_axis_contract"],
        expected: "inspect semantic axes before sizes",
        successDetail: "Axis semantics are checked before numeric allclose.",
        failureDetail: "Dimension sizes alone do not identify B/H/T/D."
      },
      {
        id: "debug_patch",
        label: "Patch Summary",
        nodeId: "trap_patch",
        focusNodeId: "trap_patch",
        emptyLabel: "?",
        correctTagIds: ["debug_patch_rules"],
        expected: "patch operand order, K^T, carry axes",
        successDetail: "The debugger records all repair rules.",
        failureDetail: "A partial patch will miss one of the common transpose traps."
      },
      {
        id: "gauntlet_standard",
        label: "Case A",
        nodeId: "gauntlet_cases",
        focusNodeId: "gauntlet_cases",
        emptyLabel: "?",
        correctTagIds: ["case_standard"],
        expected: "standard non-equal T/D case passes",
        successDetail: "Standard QK^T contract passes.",
        failureDetail: "Case A should use the normal Q[...,T,D] @ K[...,D,T] contract."
      },
      {
        id: "gauntlet_carry",
        label: "Case B",
        nodeId: "gauntlet_cases",
        focusNodeId: "qk_contract_terminal",
        emptyLabel: "?",
        correctTagIds: ["case_carry_axes"],
        expected: "carry axes stay fixed",
        successDetail: "Carry-axis variants pass.",
        failureDetail: "Case B changes B/H and catches moved prefix axes."
      },
      {
        id: "gauntlet_td_equal",
        label: "Case C",
        nodeId: "hidden_reference",
        focusNodeId: "hidden_reference",
        emptyLabel: "?",
        correctTagIds: ["case_td_equal"],
        expected: "T==D numeric trap passes",
        successDetail: "Equal-size hidden case is validated numerically.",
        failureDetail: "T==D hides shape errors; reference allclose must decide."
      },
      {
        id: "gauntlet_operand_order",
        label: "Case D",
        nodeId: "gauntlet_result",
        focusNodeId: "gauntlet_result",
        emptyLabel: "?",
        correctTagIds: ["case_operand_order"],
        expected: "operand-order trap rejected",
        successDetail: "Operand order and score-axis semantics are correct.",
        failureDetail: "The final case rejects K @ Q^T and reversed score semantics."
      }
    ],
    probes: [
      {
        id: "transpose_probe",
        label: "Transpose Probe",
        detail: "checks axis swap and index mapping",
        budgetCost: 1,
        observations: {
          matrix_flip_switch: {
            id: "probe_matrix_switch",
            title: "A real transpose moves values",
            detail: "The row axis becomes the column axis and values mirror across the diagonal.",
            evidence: ["A shape: [R,C]", "A^T shape: [C,R]", "A[0,2] -> A^T[2,0]"],
            possibleSemantic: "2D transpose",
            confidence: "high"
          },
          matrix_flip_index: {
            id: "probe_matrix_index",
            title: "Index mapping is the proof",
            detail: "Shape labels can be faked, but mirrored cell provenance cannot.",
            evidence: ["A[1,0] -> A^T[0,1]", "all cells checked"],
            possibleSemantic: "i,j->j,i",
            confidence: "high"
          },
          rank4_carry_axes: {
            id: "probe_rank4_carry",
            title: "B/H are carry axes",
            detail: "They identify independent batches and heads; they do not participate in each T by D matrix multiply.",
            evidence: ["before: [B,H,T,D]", "after: [B,H,D,T]"],
            possibleSemantic: "keep B/H",
            confidence: "high"
          }
        }
      },
      {
        id: "matmul_probe",
        label: "MatMul Probe",
        detail: "compares inner dimensions before and after transpose",
        budgetCost: 1,
        observations: {
          inner_dim_fault: {
            id: "probe_inner_fault",
            title: "The right operand is facing the wrong way",
            detail: "A exposes N on the inner side, but stored B exposes P first.",
            evidence: ["A: [M,N]", "stored B: [P,N]", "needed right operand: [N,P]"],
            possibleSemantic: "B[P,N]",
            confidence: "high"
          },
          inner_dim_fix: {
            id: "probe_inner_fix",
            title: "Transposing B repairs the inner dimension",
            detail: "B^T turns the right operand into [N,P], so N meets N.",
            evidence: ["before: [P,N]", "after: [N,P]", "output: [M,P]"],
            possibleSemantic: "T(B)",
            confidence: "high"
          },
          inner_dim_numeric: {
            id: "probe_inner_numeric",
            title: "Reference checks values, not just shape",
            detail: "A wrong transpose can produce a plausible output shape with wrong cell values.",
            evidence: ["reference: A @ B.T", "tolerance: 1e-5"],
            possibleSemantic: "allclose",
            confidence: "medium"
          }
        }
      },
      {
        id: "qk_probe",
        label: "QK Probe",
        detail: "checks Q/K axes and score board semantics",
        budgetCost: 1,
        observations: {
          single_k_transpose: {
            id: "probe_single_k",
            title: "K tokens must become columns",
            detail: "Q token rows dot against K token columns to produce a T x T board.",
            evidence: ["Q: [T,D]", "K^T: [D,T]", "[T,D] @ [D,T] -> [T,T]"],
            possibleSemantic: "K^T",
            confidence: "high"
          },
          single_score_semantics: {
            id: "probe_single_scores",
            title: "Score cell means query token by key token",
            detail: "scores[tq, tk] is q_tq dot k_tk.",
            evidence: ["rows: query token", "columns: key token"],
            possibleSemantic: "q rows/k cols",
            confidence: "high"
          },
          multi_k_transpose: {
            id: "probe_multi_k",
            title: "Only K's last two axes swap",
            detail: "Every B/H layer performs the same [T,D] @ [D,T] operation.",
            evidence: ["Q: [B,H,T,D]", "K^T: [B,H,D,T]"],
            possibleSemantic: "K^T last axes",
            confidence: "high"
          },
          multi_carry_axes: {
            id: "probe_multi_carry",
            title: "B/H are parallel layers",
            detail: "The matmul happens independently inside each batch and head.",
            evidence: ["prefix: [B,H]", "score board inside prefix: [T,T]"],
            possibleSemantic: "keep B/H",
            confidence: "high"
          }
        }
      },
      {
        id: "debug_probe",
        label: "Debug Probe",
        detail: "diagnoses shape-passing transpose traps",
        budgetCost: 1,
        observations: {
          debug_operand_order: {
            id: "probe_debug_order",
            title: "Operand order decides score semantics",
            detail: "Q must stay on the left so rows remain query tokens.",
            evidence: ["correct: Q @ K^T", "wrong: K @ Q^T"],
            possibleSemantic: "Q left/K right",
            confidence: "high"
          },
          debug_numeric_trap: {
            id: "probe_debug_numeric",
            title: "T==D can fool shape checks",
            detail: "When T and D are equal, Q @ K may produce a shape that looks square but has wrong values.",
            evidence: ["visible shape passes", "cell provenance fails"],
            possibleSemantic: "cell trace",
            confidence: "high"
          },
          gauntlet_td_equal: {
            id: "probe_gauntlet_td_equal",
            title: "Hidden Case C is a numeric trap",
            detail: "Only reference allclose can distinguish the right source cell.",
            evidence: ["T == D", "shape ok is not proof"],
            possibleSemantic: "T==D numeric",
            confidence: "high"
          }
        }
      }
    ],
    checks: [
      {
        id: "matrix_flip_contract",
        title: "0-3A Matrix Flip",
        group: "visible",
        slotIds: ["matrix_flip_switch", "matrix_flip_shape", "matrix_flip_index"],
        expected: "A[R,C] -> A^T[C,R] and A[i,j] == A^T[j,i]",
        passDetail: "2D transpose swaps axes and preserves mirrored values.",
        failDetail: "Matrix transpose contract is incomplete.",
        focusNodeId: "transpose_2d"
      },
      {
        id: "inner_dim_repair_contract",
        title: "0-3B Inner-Dim Repair",
        group: "visible",
        slotIds: ["inner_dim_fault", "inner_dim_fix", "inner_dim_output", "inner_dim_numeric"],
        expected: "A[M,N] @ B^T[N,P] -> out[M,P] allclose reference",
        passDetail: "Transpose repairs the right operand and the output matches reference.",
        failDetail: "MatMul repair remains incomplete.",
        focusNodeId: "matmul_repair_gate"
      },
      {
        id: "higher_rank_axis_contract",
        title: "0-3C Higher-Rank Axis Swap",
        group: "behavior",
        slotIds: ["rank3_swap_axes", "rank3_carry_axis", "rank4_carry_axes", "no_full_reverse"],
        expected: "[B,T,D]->[B,D,T] and [B,H,T,D]->[B,H,D,T]",
        passDetail: "Higher-rank transpose swaps only the last two axes.",
        failDetail: "Higher-rank axis contract is wrong.",
        blockedDetail: "Higher-rank checks are blocked until 2D and MatMul transpose contracts pass.",
        focusNodeId: "axis_swap_switch"
      },
      {
        id: "single_head_qk_contract",
        title: "0-3D Single-Head QK Score",
        group: "behavior",
        slotIds: ["single_k_transpose", "single_score_shape", "single_score_semantics"],
        expected: "Q[T,D] @ K^T[D,T] -> scores[T,T]",
        passDetail: "Single-head QK score board is token-to-token.",
        failDetail: "Single-head QK contract is wrong.",
        blockedDetail: "Single-head QK is blocked until higher-rank axis contract passes.",
        focusNodeId: "single_scores"
      },
      {
        id: "multi_head_qk_contract",
        title: "0-3E Multi-Head QK Trap",
        group: "behavior",
        slotIds: ["multi_k_transpose", "multi_carry_axes", "multi_score_shape"],
        expected: "Q[B,H,T,D] @ K^T[B,H,D,T] -> scores[B,H,T,T]",
        passDetail: "Multi-head QK preserves B/H and produces T x T score boards.",
        failDetail: "Multi-head transpose trap remains unresolved.",
        blockedDetail: "Multi-head QK is blocked until single-head QK passes.",
        focusNodeId: "multi_scores"
      },
      {
        id: "trap_debugger_contract",
        title: "0-3F Trap Debugger",
        group: "reference",
        slotIds: ["debug_operand_order", "debug_numeric_trap", "debug_axis_contract", "debug_patch"],
        expected: "operand order, numeric cell source, and axis semantics all checked",
        passDetail: "Debugger catches shape-passing transpose bugs.",
        failDetail: "Trap debugger did not identify every fault class.",
        blockedDetail: "Debugger is blocked until multi-head QK passes.",
        focusNodeId: "trap_reference"
      },
      {
        id: "transpose_gauntlet_cases",
        title: "0-3X Transpose Gauntlet",
        group: "hidden",
        slotIds: ["gauntlet_standard", "gauntlet_carry", "gauntlet_td_equal", "gauntlet_operand_order"],
        expected: "standard, carry-axis, T==D numeric, and operand-order cases pass",
        passDetail: "The QK^T transpose contract generalizes across hidden cases.",
        failDetail: "Hidden Transpose Gauntlet failed.",
        blockedDetail: "Hidden tests are blocked until debugger/reference checks pass.",
        focusNodeId: "gauntlet_result"
      }
    ],
    hiddenCases: [
      "Case A: Q[1,2,4,3] @ K^T[1,2,3,4]",
      "Case B: Q[2,1,8,16] @ K^T[2,1,16,8] preserves B/H",
      "Case C: T == D numeric trap Q[1,2,4,4]",
      "Case D: operand order reversed and score axes swapped"
    ],
    successSummary: "Transpose Trap repaired: 2D transpose, inner-dim repair, higher-rank axis swap, QK^T score boards, debugger, and hidden gauntlet all pass."
  },
  traceSteps: [
    { id: "03_step_matrix", title: "Matrix Flip", state: "warn", detail: "[R,C] -> [C,R]", selectNodeId: "transpose_2d" },
    { id: "03_step_inner", title: "Inner Dim", state: "warn", detail: "A[M,N] @ B^T[N,P]", selectNodeId: "matmul_repair_gate" },
    { id: "03_step_axes", title: "Axis Swap", state: "warn", detail: "swap(-2,-1)", selectNodeId: "axis_swap_switch" },
    { id: "03_step_single", title: "Single QK", state: "warn", detail: "[T,D]@[D,T]", selectNodeId: "single_scores" },
    { id: "03_step_multi", title: "Multi QK", state: "warn", detail: "[B,H,T,T]", selectNodeId: "multi_scores" },
    { id: "03_step_debug", title: "Debugger", state: "warn", detail: "shape + numeric", selectNodeId: "trap_reference" },
    { id: "03_step_gauntlet", title: "Gauntlet", state: "warn", detail: "hidden T==D", selectNodeId: "gauntlet_result" }
  ]
};
