import type { BootcampLevel, CheckState, ProbeTool, RepairCheckDefinition, RepairSlot, RepairTag, TensorEdge, TensorNode } from "./workbenchTypes";
import { encodeToyBatch, encodeToyText, hiddenTextSet, toyMergeRules, toyVocab, visibleTextSet } from "./toyTokenizer";

type NodeSpec = Omit<TensorNode, "stats" | "sample" | "checks"> & {
  stats?: TensorNode["stats"];
  sample?: string[];
  checks?: TensorNode["checks"];
};

const defaultStats = { min: "-", max: "-", mean: "-" };
const visibleBatch = encodeToyBatch(["we train llm.", "tokenizers are useful!"], { maxLength: 8, padToLength: 8 });
const sampleEncode = encodeToyText("we train useful tokenizers.", { maxLength: 8, padToLength: 8 });

function node(spec: NodeSpec): TensorNode {
  return {
    ...spec,
    stats: spec.stats ?? defaultStats,
    sample: spec.sample ?? [],
    checks: spec.checks ?? [check("inspectable", "pass", "click to inspect this tokenizer pipeline component")]
  };
}

function edge(id: string, from: string, to: string, label: string, color = 0x38bdf8, flow: TensorEdge["flow"] = "forward"): TensorEdge {
  return { id, from, to, label, color, flow, route: "direct" };
}

function check(label: string, state: CheckState, detail: string) {
  return { label, state, detail };
}

function tag(id: string, label: string, shortLabel: string, detail: string, category: NonNullable<RepairTag["category"]>): RepairTag {
  return { id, label, shortLabel, detail, category };
}

function slot(
  id: string,
  label: string,
  nodeId: string,
  tagId: string,
  expected: string,
  successDetail: string,
  failureDetail: string,
  focusNodeId = nodeId
): RepairSlot {
  return {
    id,
    label,
    nodeId,
    focusNodeId,
    emptyLabel: "unset",
    correctTagIds: [tagId],
    expected,
    successDetail,
    failureDetail
  };
}

function repairCheck(
  id: string,
  title: string,
  group: RepairCheckDefinition["group"],
  slotIds: string[],
  expected: string,
  passDetail: string,
  failDetail: string,
  focusNodeId: string,
  blockedDetail?: string
): RepairCheckDefinition {
  return { id, title, group, slotIds, expected, passDetail, failDetail, focusNodeId, blockedDetail };
}

const tags: RepairTag[] = [
  tag("raw_text_is_utf8_object", "Raw text is a UTF-8 text object", "utf8 text", "Text can be inspected, but it is not numeric model input.", "object"),
  tag("inspect_text_metadata", "Inspect text length and characters", "inspect", "Use a text inspector before treating content as model data.", "operation"),
  tag("raw_text_not_numeric_tensor", "Raw text is not a numeric tensor", "not tensor", "Embedding lookup cannot consume raw strings.", "contract"),
  tag("raw_text_is_tensor_float", "Treat text as float tensor", "float text", "Incorrect: text bytes are not token ids or embeddings.", "contract"),
  tag("connect_raw_text_to_type_gate", "Route raw text into Type Gate", "type gate", "Use the gate to expose the expected failure.", "data"),
  tag("reject_string_for_embedding", "Reject string input at numeric port", "reject str", "The model side expects integer token ids, not strings.", "contract"),
  tag("embedding_requires_int_ids", "Embedding requires integer token ids", "int ids", "Embedding lookup indexes rows with integer ids.", "embedding"),
  tag("send_raw_text_to_embedding", "Send raw text directly to Embedding", "raw->emb", "Incorrect: this bypasses tokenization.", "data"),
  tag("insert_tokenizer_socket", "Insert Tokenizer Socket", "tokenizer", "The socket converts text into token pieces.", "operation"),
  tag("utf8_to_token_pieces", "Convert UTF-8 text into token pieces", "pieces", "Tokenizer output is pieces before vocab lookup.", "token"),
  tag("block_raw_bypass", "Block raw text bypass", "no bypass", "Every model path must go through tokenizer before embedding.", "contract"),
  tag("token_pieces_are_ids", "Treat token pieces as final ids", "pieces=id", "Incorrect: pieces still need vocab lookup.", "token"),
  tag("emit_int_token_ids", "Emit integer token ids", "emit ids", "Token ids are the first numeric representation.", "token"),
  tag("token_ids_rank_1", "Single text produces token_ids[T]", "ids[T]", "One input string becomes a one-dimensional sequence of ids.", "rank"),
  tag("ids_can_index_embedding", "Ids can index embedding rows", "index rows", "Each id points to one vocab / embedding row.", "embedding"),
  tag("split_on_spaces", "Split at word boundaries", "space", "Whitespace creates candidate token boundaries.", "operation"),
  tag("split_punctuation", "Keep punctuation as separate pieces", "punct", "Punctuation must not be silently dropped.", "token"),
  tag("preserve_piece_order", "Preserve original piece order", "order", "Token order becomes the T axis order.", "semantic"),
  tag("drop_punctuation", "Drop punctuation pieces", "drop punct", "Incorrect: this loses visible symbols.", "operation"),
  tag("char_policy_many_tokens", "Character split creates many tokens", "char cost", "Char split is robust but usually expensive.", "token"),
  tag("word_policy_oov_risk", "Word split has OOV risk", "word OOV", "Whole words are compact but fragile with rare words.", "token"),
  tag("subword_policy_balanced", "Subword split balances cost and coverage", "subword", "Subwords reduce OOV while keeping token count lower than chars.", "token"),
  tag("choose_char_always", "Always choose character split", "char only", "Incorrect for the main pipeline: it wastes budget.", "token"),
  tag("count_tokens_after_split", "Count tokens after split / merge", "count", "Budget checks must use the current piece list.", "operation"),
  tag("budget_t_le_8", "Token budget T <= 8", "T<=8", "This chapter uses a visible max sequence length of 8.", "shape"),
  tag("meter_blocks_overflow", "Meter blocks sequence overflow", "block >T", "Overflow should be visible before buffer construction.", "contract"),
  tag("ignore_budget", "Ignore token budget", "ignore T", "Incorrect: later tensors need rectangular shape.", "contract"),
  tag("merge_train_ing", "Merge train + ing -> training", "training", "A merge rule combines frequent adjacent pieces.", "token"),
  tag("merge_tokenizer_s", "Merge tokenizer + s -> tokenizers", "tokenizers", "Merge order must be deterministic.", "token"),
  tag("merge_reduces_count", "Merge reduces token count", "less T", "Merges often preserve meaning while lowering T.", "operation"),
  tag("preserve_space_marker", "Preserve a visible space marker", "space mark", "Debug views need to reveal word starts or spacing.", "token"),
  tag("preserve_symbols", "Preserve visible symbols", "symbols", "Punctuation and symbols remain part of the stream.", "token"),
  tag("decode_debug_possible", "Keep enough data for decode check", "decode", "A reversible debug view helps catch dropped pieces.", "semantic"),
  tag("lookup_all_pieces", "Lookup every piece in vocab", "lookup all", "Each token piece must map to a vocab row or fallback.", "operation"),
  tag("flag_missing_vocab", "Flag missing vocab piece", "flag OOV", "Unresolved pieces are errors until fallback handles them.", "contract"),
  tag("emit_vocab_ids", "Emit vocab row ids", "vocab ids", "The output stream is integer row addresses.", "token"),
  tag("skip_vocab_lookup", "Skip vocab lookup", "skip vocab", "Incorrect: embedding rows need stable ids.", "operation"),
  tag("piece_lights_row", "Piece lights exactly one vocab row", "row light", "A resolved piece selects one vocab row.", "semantic"),
  tag("id_is_row_address", "Token id is row address", "id=row", "The id is not an arbitrary score; it is a table address.", "contract"),
  tag("embedding_row_probe", "Embedding probe reads selected row", "row probe", "Use the token id to inspect the embedding row.", "embedding"),
  tag("same_piece_same_id", "Same piece always maps to same id", "stable id", "Stable ids are required across calls and batches.", "contract"),
  tag("deterministic_run", "Repeated encode is deterministic", "deterministic", "The same input and vocab produce identical ids.", "operation"),
  tag("no_random_vocab", "No random vocab allocation", "no random", "Runtime must not invent new ids during encode.", "contract"),
  tag("random_id_allocator", "Allocate random ids for new pieces", "random ids", "Incorrect: this breaks reproducibility.", "operation"),
  tag("buffer_axis_b", "Rows are batch axis B", "B rows", "Each row is one independent text sample.", "axis"),
  tag("buffer_axis_t", "Columns are token axis T", "T cols", "Columns preserve position within each sample.", "axis"),
  tag("rectangular_token_buffer", "Build rectangular int[B,T] buffer", "int[B,T]", "Batch execution needs a rectangular integer tensor.", "shape"),
  tag("detect_oov", "Detect out-of-vocabulary pieces", "detect OOV", "OOV pieces must be visible in trace.", "operation"),
  tag("block_unresolved_oov", "Block unresolved OOV from ids", "block OOV", "Do not send unresolved text pieces into embedding lookup.", "contract"),
  tag("oov_report_piece", "Report exact unresolved piece", "report", "Helpful failure feedback names the piece that failed.", "semantic"),
  tag("fallback_subword", "Fallback to smaller subword pieces", "subword fb", "Try known sub-pieces before giving up.", "operation"),
  tag("fallback_char", "Fallback to character pieces", "char fb", "Character fallback can cover rare words with higher cost.", "operation"),
  tag("fallback_unk", "Fallback to <unk> id", "<unk>", "Unknown fallback gives a stable reserved id.", "token"),
  tag("inject_bos", "Inject <bos> at sequence start", "<bos>", "BOS marks the beginning of a sequence.", "token"),
  tag("inject_eos", "Inject <eos> after content", "<eos>", "EOS marks where content ends.", "token"),
  tag("reserve_special_ids", "Reserve ids for special tokens", "reserved", "PAD/BOS/EOS/UNK must keep stable ids.", "contract"),
  tag("right_padding", "Pad on the right after EOS", "right pad", "Padding fills unused T positions after content.", "operation"),
  tag("pad_id_zero", "<pad> uses id 0", "pad=0", "The toy vocab reserves row 0 for padding.", "token"),
  tag("attention_mask_matches_pad", "Attention mask is 1 for content and 0 for pad", "mask", "The mask must match padded positions exactly.", "mask"),
  tag("left_padding", "Pad on the left before BOS", "left pad", "Incorrect for this chapter's visible contract.", "operation"),
  tag("mask_all_ones", "Use all-ones attention mask", "all ones", "Incorrect: padding positions must be masked out.", "mask"),
  tag("apply_token_budget", "Apply max token budget", "budget", "The pipeline must enforce max T before batch output.", "contract"),
  tag("truncate_or_reject", "Truncate or reject over-budget sequence", "truncate", "A sequence cannot silently overflow the buffer.", "operation"),
  tag("budget_trace", "Trace which pieces consumed budget", "trace T", "Good feedback shows why the budget failed.", "semantic"),
  tag("gauntlet_type_contract", "Type contract passes", "type", "No raw text reaches numeric model ports.", "contract"),
  tag("gauntlet_piece_contract", "Piece contract passes", "pieces", "Splitting and merge policy preserve intended pieces.", "token"),
  tag("gauntlet_vocab_contract", "Vocab contract passes", "vocab", "All output tokens resolve to stable vocab ids.", "contract"),
  tag("gauntlet_fallback_contract", "Fallback contract passes", "fallback", "OOV handling is deterministic and explicit.", "operation"),
  tag("gauntlet_special_contract", "Special token contract passes", "special", "BOS/EOS/PAD/UNK ids are reserved and placed correctly.", "token"),
  tag("gauntlet_batch_contract", "Batch buffer contract passes", "batch", "Outputs are rectangular int[B,T] tensors.", "shape"),
  tag("gauntlet_mask_contract", "Mask contract passes", "mask", "attention_mask[B,T] exactly mirrors padding.", "mask"),
  tag("gauntlet_determinism_contract", "Determinism contract passes", "stable", "Two runs produce identical pieces and ids.", "contract"),
  tag("gauntlet_budget_contract", "Budget contract passes", "budget", "Hidden over-budget texts are rejected or truncated with trace.", "contract"),
  tag("gauntlet_embedding_ready", "Embedding lookup is ready", "embed ok", "Final token ids can index embedding rows safely.", "embedding")
];

const slots: RepairSlot[] = [
  slot("c1_raw_text_object", "Raw text object", "raw_text_input", "raw_text_is_utf8_object", "utf8 text object", "Raw text is treated as inspectable text, not tensor data.", "Raw input still lacks a text-object contract."),
  slot("c1_text_inspector_open", "Text inspector", "text_inspector", "inspect_text_metadata", "length / chars visible", "Inspector can show length, characters, and sample bytes.", "Open the inspector before sending text downstream."),
  slot("c1_not_numeric_tensor", "Numeric gate", "type_gate", "raw_text_not_numeric_tensor", "not numeric tensor", "The gate correctly marks text as non-numeric.", "Raw text is being treated like numeric tensor data."),
  slot("c1_type_gate_input", "Gate input", "type_gate", "connect_raw_text_to_type_gate", "raw text -> gate", "Raw text is routed into the Type Gate for a controlled failure.", "Expose the failure through the Type Gate first."),
  slot("c1_type_gate_failure", "Failure reason", "type_gate", "reject_string_for_embedding", "reject string", "The gate rejects string input at numeric ports.", "The failure reason should be string input at a numeric port."),
  slot("c1_embedding_requires_ids", "Embedding contract", "raw_embedding_probe", "embedding_requires_int_ids", "integer ids", "Embedding lookup now states it needs int token ids.", "Embedding lookup still has no clear input contract."),
  slot("c1_tokenizer_socket", "Tokenizer socket", "tokenizer_socket", "insert_tokenizer_socket", "insert tokenizer", "Tokenizer Socket is placed between text and model input.", "Insert Tokenizer Socket before any numeric model module."),
  slot("c1_tokenizer_input_contract", "Tokenizer output", "token_piece_stream", "utf8_to_token_pieces", "token pieces", "The tokenizer emits token pieces before ids.", "Tokenizer output is being confused with final ids."),
  slot("c1_raw_bypass_blocked", "Bypass guard", "tokenizer_socket", "block_raw_bypass", "no raw bypass", "Raw text bypass is blocked.", "A raw text path still reaches model-side ports."),
  slot("c1_token_id_output", "ID emitter", "token_id_emitter", "emit_int_token_ids", "integer token ids", "Token IDs are emitted as numeric addresses.", "The pipeline has not produced integer ids yet."),
  slot("c1_token_id_rank", "Single text rank", "token_id_emitter", "token_ids_rank_1", "token_ids[T]", "One text creates a T-length id vector.", "A single string should not become a batch tensor yet."),
  slot("c1_embedding_id_contract", "Embedding input", "embedding_lookup_probe", "ids_can_index_embedding", "ids index rows", "The id stream can index embedding rows.", "Embedding lookup still cannot consume the current output."),
  slot("c1_boundary_spaces", "Space boundary", "boundary_cutter", "split_on_spaces", "split spaces", "Space boundaries create candidate pieces.", "Whitespace boundaries are missing."),
  slot("c1_boundary_punctuation", "Punctuation boundary", "boundary_cutter", "split_punctuation", "split punctuation", "Punctuation is kept as its own piece.", "Punctuation was dropped or merged invisibly."),
  slot("c1_boundary_order", "Piece order", "token_piece_stream", "preserve_piece_order", "preserve order", "Token piece order matches the source text order.", "Pieces are not preserving the original order."),
  slot("c1_compare_char_policy", "Char policy", "split_policy_switch", "char_policy_many_tokens", "many robust tokens", "Character split is identified as robust but costly.", "Char split cost is not being accounted for."),
  slot("c1_compare_word_policy", "Word policy", "split_policy_switch", "word_policy_oov_risk", "compact but OOV", "Word split is identified as compact but brittle.", "Word split OOV risk is missing."),
  slot("c1_compare_subword_policy", "Subword policy", "split_policy_switch", "subword_policy_balanced", "balanced default", "Subword split is selected as the default tradeoff.", "The policy comparison should land on subword default."),
  slot("c1_count_meter_input", "Count source", "token_count_meter", "count_tokens_after_split", "count current pieces", "Meter counts after split and merge.", "Count must happen after the current split policy."),
  slot("c1_count_budget", "Visible budget", "token_count_meter", "budget_t_le_8", "T <= 8", "The visible max length is enforced.", "The budget limit is missing."),
  slot("c1_count_fail_fast", "Overflow behavior", "token_count_meter", "meter_blocks_overflow", "block overflow", "Overflow is blocked before buffer construction.", "Overflow is silently passing through."),
  slot("c1_merge_train_ing", "Merge train+ing", "merge_forge", "merge_train_ing", "training", "train + ing merges into training.", "The training merge rule is missing."),
  slot("c1_merge_tokenizer_s", "Merge tokenizer+s", "merge_forge", "merge_tokenizer_s", "tokenizers", "tokenizer + s merges into tokenizers.", "Plural tokenizer merge is missing."),
  slot("c1_merge_count", "Merge effect", "token_count_meter", "merge_reduces_count", "lower T", "Merge Forge reduces token count without changing order.", "Merge effect is not reflected in count."),
  slot("c1_preserve_space_marker", "Space marker", "symbol_keeper", "preserve_space_marker", "space visible", "Space or word-start markers stay visible in debug.", "Spacing information disappeared from debug output."),
  slot("c1_preserve_punctuation", "Symbol preservation", "symbol_keeper", "preserve_symbols", "symbols kept", "Punctuation survives tokenization.", "Symbols were discarded."),
  slot("c1_preserve_reversible_debug", "Decode debug", "symbol_keeper", "decode_debug_possible", "decode check", "Debug output can detect dropped pieces.", "There is not enough information for a decode check."),
  slot("c1_lookup_vocab_rows", "Vocab lookup", "vocab_lookup_gate", "lookup_all_pieces", "all pieces", "Every piece is sent to vocab lookup.", "Some pieces bypass vocab lookup."),
  slot("c1_lookup_unknown_flag", "Missing row flag", "vocab_lookup_gate", "flag_missing_vocab", "flag missing", "Missing vocab rows are flagged.", "Missing vocab entries are not visible."),
  slot("c1_lookup_emit_ids", "Lookup output", "token_id_emitter", "emit_vocab_ids", "row ids", "Lookup emits integer row ids.", "Lookup is not producing vocab ids."),
  slot("c1_address_piece_row", "Row lighting", "address_lighting", "piece_lights_row", "one row", "Each piece lights its vocab row.", "Pieces are not tied to exact rows."),
  slot("c1_address_id_equals_row", "ID meaning", "address_lighting", "id_is_row_address", "id=row", "Token id is understood as a row address.", "ID meaning is still arbitrary."),
  slot("c1_address_embedding_probe", "Embedding probe", "embedding_lookup_probe", "embedding_row_probe", "read row", "Embedding probe reads the selected row.", "Embedding row lookup is not proven."),
  slot("c1_stable_same_piece", "Same piece", "stable_id_checker", "same_piece_same_id", "same id", "Same piece maps to same id.", "Same piece can change id."),
  slot("c1_stable_repeat_run", "Repeat run", "stable_id_checker", "deterministic_run", "same run", "Repeated encode is deterministic.", "Repeated encode is not stable."),
  slot("c1_stable_no_random_vocab", "No runtime vocab", "stable_id_checker", "no_random_vocab", "no new ids", "Runtime cannot invent new vocab ids.", "New ids are being created during encode."),
  slot("c1_buffer_axis_b", "Buffer rows", "token_buffer", "buffer_axis_b", "B rows", "Rows are batch samples.", "Rows are not labeled as B."),
  slot("c1_buffer_axis_t", "Buffer columns", "token_buffer", "buffer_axis_t", "T columns", "Columns are token positions.", "Columns are not labeled as T."),
  slot("c1_buffer_rectangular", "Buffer shape", "token_buffer", "rectangular_token_buffer", "int[B,T]", "Batch output is a rectangular int[B,T] buffer.", "Batch output is ragged or non-integer."),
  slot("c1_oov_detector", "OOV detector", "oov_detector", "detect_oov", "detect OOV", "OOV pieces are detected.", "OOV pieces are invisible."),
  slot("c1_oov_block", "OOV block", "oov_detector", "block_unresolved_oov", "block unresolved", "Unresolved OOV cannot reach embedding lookup.", "Unresolved pieces still reach ids."),
  slot("c1_oov_report", "OOV report", "oov_detector", "oov_report_piece", "report piece", "Failure feedback names the unresolved piece.", "Feedback does not identify the bad piece."),
  slot("c1_fallback_subword", "Subword fallback", "fallback_splitter", "fallback_subword", "subword", "Fallback first tries smaller known pieces.", "Fallback should start with subword decomposition."),
  slot("c1_fallback_char", "Character fallback", "fallback_splitter", "fallback_char", "chars", "Character fallback can cover rare text at higher cost.", "Character fallback is missing."),
  slot("c1_fallback_unk", "Unknown fallback", "fallback_splitter", "fallback_unk", "<unk>", "Remaining unknowns map to reserved <unk>.", "Unknowns need a stable fallback id."),
  slot("c1_special_bos", "BOS token", "special_token_injector", "inject_bos", "<bos>", "BOS is injected at sequence start.", "BOS is missing or misplaced."),
  slot("c1_special_eos", "EOS token", "special_token_injector", "inject_eos", "<eos>", "EOS is injected after content.", "EOS is missing or misplaced."),
  slot("c1_special_reserved", "Reserved ids", "special_token_injector", "reserve_special_ids", "reserved ids", "Special ids remain reserved and stable.", "Special token ids are not reserved."),
  slot("c1_padding_side", "Padding side", "padding_builder", "right_padding", "right pad", "Padding is added after EOS/content.", "Padding side is wrong."),
  slot("c1_padding_id", "Pad id", "padding_builder", "pad_id_zero", "pad id 0", "Padding uses id 0.", "Pad id should be the reserved zero row."),
  slot("c1_mask_matches_pad", "Pad mask", "attention_mask_builder", "attention_mask_matches_pad", "1 content / 0 pad", "Attention mask exactly matches pad positions.", "Mask and pad positions disagree."),
  slot("c1_budget_policy", "Budget gate", "budget_gate", "apply_token_budget", "apply max T", "Max T is enforced.", "Max token budget is not enforced."),
  slot("c1_budget_truncate", "Over-budget action", "budget_gate", "truncate_or_reject", "truncate/reject", "Over-budget text is truncated or rejected with EOS safety.", "Over-budget text overflows silently."),
  slot("c1_budget_trace", "Budget trace", "budget_gate", "budget_trace", "trace pieces", "Trace shows which pieces consumed T.", "Budget failure lacks useful trace."),
  slot("c1_gauntlet_type_contract", "Type contract", "tokenizer_contract_terminal", "gauntlet_type_contract", "no raw text", "Type contract passes.", "Raw text can still reach numeric ports."),
  slot("c1_gauntlet_piece_contract", "Piece contract", "tokenizer_contract_terminal", "gauntlet_piece_contract", "pieces valid", "Piece contract passes.", "Split/merge behavior is not stable."),
  slot("c1_gauntlet_vocab_contract", "Vocab contract", "tokenizer_contract_terminal", "gauntlet_vocab_contract", "vocab ids", "Vocab contract passes.", "Some tokens do not resolve to stable ids."),
  slot("c1_gauntlet_fallback_contract", "Fallback contract", "tokenizer_contract_terminal", "gauntlet_fallback_contract", "OOV handled", "Fallback contract passes.", "OOV handling is incomplete."),
  slot("c1_gauntlet_special_contract", "Special contract", "tokenizer_contract_terminal", "gauntlet_special_contract", "special ok", "Special token contract passes.", "Special tokens are wrong."),
  slot("c1_gauntlet_batch_contract", "Batch contract", "tokenizer_contract_terminal", "gauntlet_batch_contract", "int[B,T]", "Batch contract passes.", "Batch output is not rectangular."),
  slot("c1_gauntlet_mask_contract", "Mask contract", "tokenizer_contract_terminal", "gauntlet_mask_contract", "mask ok", "Mask contract passes.", "Attention mask does not match padding."),
  slot("c1_gauntlet_determinism_contract", "Determinism", "tokenizer_contract_terminal", "gauntlet_determinism_contract", "stable", "Determinism contract passes.", "Tokenizer output changes between runs."),
  slot("c1_gauntlet_budget_contract", "Budget contract", "tokenizer_contract_terminal", "gauntlet_budget_contract", "budget ok", "Budget contract passes.", "Hidden budget case fails."),
  slot("c1_gauntlet_embedding_contract", "Embedding ready", "embedding_lookup_probe", "gauntlet_embedding_ready", "embed ok", "Embedding lookup can consume final ids.", "Final ids are not embedding-ready.")
];

const probes: ProbeTool[] = [
  {
    id: "text_probe",
    label: "Text Probe",
    detail: "Inspect raw text type, length, and numeric compatibility.",
    budgetCost: 1,
    observations: {
      c1_raw_text_object: {
        id: "text_probe_raw",
        title: "Raw text is not numeric",
        detail: "The value is UTF-8 text with characters and length, not float/int tensor data.",
        evidence: ["dtype: utf8", "sample: 'we train llm.'", "numeric rank: none"],
        possibleSemantic: "text object",
        confidence: "high"
      },
      c1_embedding_requires_ids: {
        id: "text_probe_embedding",
        title: "Embedding port contract",
        detail: "The embedding port accepts integer row addresses only.",
        evidence: ["expected dtype: int64", "received dtype: utf8"],
        possibleSemantic: "integer ids",
        confidence: "high"
      }
    }
  },
  {
    id: "split_probe",
    label: "Split Probe",
    detail: "Compare word, char, and subword split outputs.",
    budgetCost: 1,
    observations: {
      c1_compare_subword_policy: {
        id: "split_probe_policy",
        title: "Subword tradeoff",
        detail: "Subword split keeps token count lower than char split while reducing OOV compared with word split.",
        evidence: ["char: 24 pieces", "word: 3 pieces + OOV", "subword: 5 pieces, resolvable"],
        possibleSemantic: "subword policy",
        confidence: "high"
      },
      c1_merge_count: {
        id: "split_probe_merge",
        title: "Merge reduces T",
        detail: "train + ing and tokenizer + s merge into known vocab entries.",
        evidence: toyMergeRules.map(([left, right, merged]) => `${left}+${right}->${merged}`),
        possibleSemantic: "merge rule",
        confidence: "high"
      }
    }
  },
  {
    id: "vocab_probe",
    label: "Vocab Probe",
    detail: "Inspect vocab row addresses and stable id behavior.",
    budgetCost: 1,
    observations: {
      c1_address_id_equals_row: {
        id: "vocab_probe_row",
        title: "ID equals row address",
        detail: "Known pieces resolve to fixed integer rows in the toy vocab.",
        evidence: [`token -> ${toyVocab.token}`, `training -> ${toyVocab.training}`, `<unk> -> ${toyVocab["<unk>"]}`],
        possibleSemantic: "vocab row",
        confidence: "high"
      },
      c1_stable_repeat_run: {
        id: "vocab_probe_stable",
        title: "Repeated encode is stable",
        detail: "Two runs of the same text produce identical token ids.",
        evidence: [`ids: ${sampleEncode.ids.join(", ")}`, `tokens: ${sampleEncode.tokens.join(" ")}`],
        possibleSemantic: "deterministic tokenizer",
        confidence: "high"
      }
    }
  },
  {
    id: "buffer_probe",
    label: "Buffer Probe",
    detail: "Inspect final token_ids[B,T] and attention_mask[B,T].",
    budgetCost: 1,
    observations: {
      c1_buffer_rectangular: {
        id: "buffer_probe_shape",
        title: "Rectangular batch",
        detail: "Batch output is padded to a rectangular int[B,T] tensor.",
        evidence: [`token_ids shape: [${visibleBatch.tokenIds.length},${visibleBatch.tokenIds[0]?.length ?? 0}]`, `row0: ${visibleBatch.tokenIds[0]?.join(", ")}`],
        possibleSemantic: "token buffer",
        confidence: "high"
      },
      c1_mask_matches_pad: {
        id: "buffer_probe_mask",
        title: "Mask mirrors pad",
        detail: "Pad positions use id 0 and attention mask 0.",
        evidence: [`mask row0: ${visibleBatch.attentionMask[0]?.join(", ")}`, `mask row1: ${visibleBatch.attentionMask[1]?.join(", ")}`],
        possibleSemantic: "attention mask",
        confidence: "high"
      }
    }
  }
];

export const chapter1TokenizationLevel: BootcampLevel = {
  id: "1-1",
  title: "Text -> Token",
  subtitle: "Build a deterministic tokenizer input pipeline",
  objective:
    "按 1-1A 到 1-X 的阶梯挑战，把 raw text 转成 token pieces、稳定 vocab ids、special tokens、padding 和 attention_mask，最终输出 token_ids[B,T]。",
  sceneTitle: "Chapter 1 - Text -> Token",
  sceneSubtitle: "Unpack the tokenizer black box: type contract, split policy, vocab addressing, OOV fallback, special tokens, padding, and batch buffer.",
  defaultSelectedNodeId: "raw_text_input",
  briefing: [
    "Chapter 0 已经证明模型内部消费的是 tensor，不是自然语言字符串。",
    "本章把 tokenizer 黑盒拆开：文字先成为 token pieces，再通过 vocab 变成稳定整数 id。",
    "最终目标是可测试的 token_ids[B,T] 与 attention_mask[B,T]。"
  ],
  knowledgeCards: [
    {
      title: "Chapter 1 Text -> Token",
      body:
        "Raw text cannot flow directly into embedding lookup.\n\nTokenizer 的任务不是“理解文字”，而是把可变长文本变成稳定、可批处理、可查表的整数地址。",
      visual: ["raw text", "split pieces", "vocab ids", "special tokens", "pad + mask", "int[B,T]"]
    }
  ],
  knowledgeTransition: {
    title: "Tokenizer Workbench",
    body:
      "进入画布后，从 1-1A 开始。先故意观察 raw text 为什么不能进模型，再逐步修出完整 tokenizer contract。\n\n细分小节以 Chapter 1 full gameplay 文档为准。",
    buttonLabel: "Start Chapter 1"
  },
  mission: {
    title: "Repair Mission: Text -> Token Pipeline",
    body:
      "当前训练板会按 1-1 / 1-2 / 1-3 / 1-4 / 1-X 解锁。每一步只修一个合同：类型、切分、词表地址、OOV、special token、padding、mask 和最终 batch buffer。",
    success: [
      "Raw text 不再能绕过 tokenizer。",
      "所有 pieces 都解析成稳定 vocab ids 或显式 fallback。",
      "最终输出 token_ids[B,T]、attention_mask[B,T] 和可调试 tokens[B,T]。"
    ]
  },
  unlocks: ["Tokenizer Socket", "Boundary Cutter", "Toy Vocab", "Fallback Splitter", "Special Token Injector", "Padding Builder", "Token Buffer"],
  contracts: [
    "input: raw_text[B] / utf8 strings",
    "split: deterministic token pieces with preserved order",
    "lookup: token piece -> vocab row id",
    "output: token_ids[B,T] int64 + attention_mask[B,T]",
    "hidden tests: punctuation, OOV, padding, budget, determinism"
  ],
  nodes: [
    node({
      id: "raw_text_input",
      title: "Text Input Node",
      subtitle: "raw utf8 string",
      kind: "source",
      semanticName: "raw_text",
      dtype: "utf8",
      shape: "scalar string / [B]",
      source: "dataset text",
      consumer: "text inspector",
      sample: visibleTextSet,
      checks: [check("type", "warn", "raw text is inspectable but not numeric")],
      x: 150,
      y: 260,
      w: 184,
      h: 96,
      color: 0x1a4164
    }),
    node({
      id: "text_inspector",
      title: "Text Inspector",
      subtitle: "length / chars / bytes",
      kind: "operation",
      semanticName: "text_inspector",
      dtype: "tool",
      shape: "metadata",
      source: "raw text",
      consumer: "type gate",
      sample: ["len('we train llm.') = 13", "chars visible", "not numeric"],
      x: 430,
      y: 250,
      w: 190,
      h: 104,
      color: 0x304b6a
    }),
    node({
      id: "type_gate",
      title: "Type Gate",
      subtitle: "numeric port guard",
      kind: "scalar",
      semanticName: "type_contract",
      dtype: "bool",
      shape: "utf8 != int",
      source: "text inspector",
      consumer: "tokenizer socket",
      sample: ["expected: int ids", "received: utf8 text", "status: blocked"],
      checks: [check("contract", "warn", "strings must be tokenized before embedding lookup")],
      x: 720,
      y: 260,
      w: 178,
      h: 92,
      color: 0x74491a
    }),
    node({
      id: "raw_embedding_probe",
      title: "Embedding Port",
      subtitle: "rejects raw text",
      kind: "operation",
      semanticName: "embedding_input_contract",
      dtype: "int64 ids",
      shape: "[T] or [B,T]",
      source: "token ids",
      consumer: "embedding table",
      sample: ["row index required", "raw string rejected"],
      x: 1000,
      y: 258,
      w: 184,
      h: 96,
      color: 0x4c2f72
    }),
    node({
      id: "tokenizer_socket",
      title: "Tokenizer Socket",
      subtitle: "utf8 -> pieces",
      kind: "operation",
      semanticName: "tokenizer",
      dtype: "op",
      shape: "text -> pieces",
      source: "raw text",
      consumer: "piece stream",
      sample: ["we train llm.", "-> we / train / llm / ."],
      x: 430,
      y: 260,
      w: 194,
      h: 98,
      color: 0x304b6a
    }),
    node({
      id: "token_piece_stream",
      title: "Token Piece Stream",
      subtitle: "ordered pieces",
      kind: "tensor",
      semanticName: "token_pieces",
      dtype: "string[]",
      shape: "[T pieces]",
      source: "tokenizer socket",
      consumer: "vocab lookup",
      sample: sampleEncode.pieces,
      x: 720,
      y: 252,
      w: 210,
      h: 112,
      color: 0x1f6f54
    }),
    node({
      id: "token_id_emitter",
      title: "Token ID Emitter",
      subtitle: "pieces -> int ids",
      kind: "operation",
      semanticName: "id_emitter",
      dtype: "int64",
      shape: "[T]",
      source: "vocab lookup",
      consumer: "embedding lookup",
      sample: [`tokens: ${sampleEncode.tokens.join(" ")}`, `ids: ${sampleEncode.ids.join(", ")}`],
      x: 1010,
      y: 254,
      w: 218,
      h: 110,
      color: 0x304b6a
    }),
    node({
      id: "embedding_lookup_probe",
      title: "Embedding Lookup Probe",
      subtitle: "row address check",
      kind: "operation",
      semanticName: "embedding_probe",
      dtype: "float32",
      shape: "id -> row[C]",
      source: "token ids",
      consumer: "Chapter 2 embedding",
      sample: [`token id ${toyVocab.token} -> embedding row ${toyVocab.token}`, "<pad> id 0 masked"],
      x: 1260,
      y: 260,
      w: 214,
      h: 98,
      color: 0x4c2f72
    }),
    node({
      id: "boundary_cutter",
      title: "Boundary Cutter",
      subtitle: "space / punctuation",
      kind: "operation",
      semanticName: "boundary_cutter",
      dtype: "op",
      shape: "text -> pieces",
      source: "raw text",
      consumer: "split policy",
      sample: ["shape, token buffer", "-> shape / , / token / buffer"],
      x: 210,
      y: 250,
      w: 210,
      h: 106,
      color: 0x304b6a
    }),
    node({
      id: "split_policy_switch",
      title: "Split Policy Switch",
      subtitle: "char / word / subword",
      kind: "operation",
      semanticName: "split_policy",
      dtype: "policy",
      shape: "strategy",
      source: "boundary cutter",
      consumer: "token count meter",
      sample: ["char: robust / high T", "word: compact / OOV", "subword: balanced"],
      x: 510,
      y: 248,
      w: 226,
      h: 112,
      color: 0x304b6a
    }),
    node({
      id: "token_count_meter",
      title: "Token Count Meter",
      subtitle: "budget T <= 8",
      kind: "scalar",
      semanticName: "token_budget",
      dtype: "int",
      shape: "T count",
      source: "pieces",
      consumer: "budget gate",
      sample: ["visible max T = 8", `sample ids: ${sampleEncode.ids.length}`],
      x: 820,
      y: 254,
      w: 204,
      h: 104,
      color: 0x74491a
    }),
    node({
      id: "merge_forge",
      title: "Merge Forge",
      subtitle: "BPE-style merges",
      kind: "operation",
      semanticName: "merge_rules",
      dtype: "table",
      shape: `${toyMergeRules.length} rules`,
      source: "piece stream",
      consumer: "token count meter",
      sample: toyMergeRules.map(([left, right, merged]) => `${left}+${right}->${merged}`),
      x: 510,
      y: 420,
      w: 230,
      h: 112,
      color: 0x304b6a
    }),
    node({
      id: "symbol_keeper",
      title: "Preserve Symbols",
      subtitle: "spaces / punctuation debug",
      kind: "operation",
      semanticName: "symbol_policy",
      dtype: "policy",
      shape: "debug view",
      source: "piece stream",
      consumer: "vocab lookup",
      sample: ["',' and '!' stay visible", "word-start marker kept in debug"],
      x: 1110,
      y: 252,
      w: 218,
      h: 106,
      color: 0x304b6a
    }),
    node({
      id: "vocab_table",
      title: "Toy Vocab Table",
      subtitle: "piece -> row id",
      kind: "matrix",
      semanticName: "vocab",
      dtype: "map<string,int>",
      shape: `[${Object.keys(toyVocab).length}]`,
      source: "fixed chapter vocab",
      consumer: "vocab lookup gate",
      sample: Object.entries(toyVocab)
        .slice(0, 12)
        .map(([piece, id]) => `${piece}: ${id}`),
      x: 190,
      y: 236,
      w: 230,
      h: 132,
      color: 0x1f6f54
    }),
    node({
      id: "vocab_lookup_gate",
      title: "Vocab Lookup Gate",
      subtitle: "resolve pieces",
      kind: "operation",
      semanticName: "vocab_lookup",
      dtype: "op",
      shape: "piece -> id",
      source: "pieces + vocab",
      consumer: "id emitter",
      sample: ["token -> 12", "useful -> 20", "missing -> OOV"],
      x: 510,
      y: 250,
      w: 214,
      h: 108,
      color: 0x304b6a
    }),
    node({
      id: "address_lighting",
      title: "Address Lighting",
      subtitle: "selected row glows",
      kind: "operation",
      semanticName: "row_address",
      dtype: "debug",
      shape: "row id",
      source: "vocab lookup",
      consumer: "embedding probe",
      sample: [`llm -> row ${toyVocab.llm}`, `tokenizer -> row ${toyVocab.tokenizer}`],
      x: 820,
      y: 250,
      w: 216,
      h: 108,
      color: 0x304b6a
    }),
    node({
      id: "stable_id_checker",
      title: "Stable ID Test",
      subtitle: "same input -> same ids",
      kind: "scalar",
      semanticName: "determinism",
      dtype: "bool",
      shape: "run A == run B",
      source: "vocab lookup",
      consumer: "token buffer",
      sample: [`run A: ${sampleEncode.ids.join(",")}`, `run B: ${sampleEncode.ids.join(",")}`],
      x: 1128,
      y: 250,
      w: 228,
      h: 108,
      color: 0x74491a
    }),
    node({
      id: "token_buffer",
      title: "Token Buffer",
      subtitle: "token_ids[B,T]",
      kind: "tensor",
      semanticName: "token_ids",
      dtype: "int64",
      shape: `[${visibleBatch.tokenIds.length},${visibleBatch.tokenIds[0]?.length ?? 0}]`,
      source: "id emitter",
      consumer: "embedding lookup",
      sample: visibleBatch.tokenIds.map((row) => `[${row.join(", ")}]`),
      x: 1120,
      y: 418,
      w: 238,
      h: 126,
      color: 0x1f6f54
    }),
    node({
      id: "oov_detector",
      title: "OOV Detector",
      subtitle: "find missing pieces",
      kind: "operation",
      semanticName: "oov_detector",
      dtype: "op",
      shape: "missing pieces",
      source: "vocab lookup",
      consumer: "fallback splitter",
      sample: ["are -> OOV", "? -> OOV", "report exact piece"],
      x: 220,
      y: 250,
      w: 210,
      h: 108,
      color: 0x74491a
    }),
    node({
      id: "fallback_splitter",
      title: "Fallback Splitter",
      subtitle: "subword / char / unk",
      kind: "operation",
      semanticName: "fallback",
      dtype: "policy",
      shape: "OOV -> ids",
      source: "OOV detector",
      consumer: "special tokens",
      sample: ["unknown -> <unk>", "rare word -> chars or subpieces"],
      x: 520,
      y: 250,
      w: 224,
      h: 108,
      color: 0x304b6a
    }),
    node({
      id: "special_token_injector",
      title: "Special Token Injector",
      subtitle: "BOS / EOS / PAD / UNK",
      kind: "operation",
      semanticName: "special_tokens",
      dtype: "op",
      shape: "reserved ids",
      source: "resolved ids",
      consumer: "padding builder",
      sample: ["<pad>=0", "<bos>=1", "<eos>=2", "<unk>=3"],
      x: 828,
      y: 250,
      w: 230,
      h: 110,
      color: 0x304b6a
    }),
    node({
      id: "padding_builder",
      title: "Padding Builder",
      subtitle: "ragged -> rectangular",
      kind: "operation",
      semanticName: "padding",
      dtype: "op",
      shape: "pad to T",
      source: "special ids",
      consumer: "attention mask",
      sample: ["right pad after EOS", "pad id = 0"],
      x: 1138,
      y: 250,
      w: 214,
      h: 108,
      color: 0x304b6a
    }),
    node({
      id: "attention_mask_builder",
      title: "Attention Mask Builder",
      subtitle: "1 content / 0 pad",
      kind: "mask",
      semanticName: "attention_mask",
      dtype: "int64",
      shape: `[${visibleBatch.attentionMask.length},${visibleBatch.attentionMask[0]?.length ?? 0}]`,
      source: "padded ids",
      consumer: "attention",
      sample: visibleBatch.attentionMask.map((row) => `[${row.join(", ")}]`),
      x: 1140,
      y: 430,
      w: 230,
      h: 118,
      color: 0x6d4c19
    }),
    node({
      id: "budget_gate",
      title: "Token Budget Gate",
      subtitle: "max T enforcement",
      kind: "scalar",
      semanticName: "token_budget_gate",
      dtype: "bool",
      shape: "T <= max",
      source: "token count meter",
      consumer: "token buffer",
      sample: ["maxLength = 8", "overflow -> truncate or reject", "trace consumed pieces"],
      x: 818,
      y: 430,
      w: 226,
      h: 110,
      color: 0x74491a
    }),
    node({
      id: "gauntlet_cases",
      title: "Tokenizer Gauntlet Cases",
      subtitle: "visible + hidden text set",
      kind: "source",
      semanticName: "test_cases",
      dtype: "utf8[]",
      shape: `[${visibleTextSet.length + hiddenTextSet.length}]`,
      source: "autograder",
      consumer: "contract terminal",
      sample: [...visibleTextSet, ...hiddenTextSet],
      x: 180,
      y: 260,
      w: 244,
      h: 130,
      color: 0x1a4164
    }),
    node({
      id: "tokenizer_contract_terminal",
      title: "Contract Terminal",
      subtitle: "autograder checks",
      kind: "operation",
      semanticName: "tokenizer_autograder",
      dtype: "tests",
      shape: "10 checks",
      source: "pipeline",
      consumer: "gauntlet result",
      sample: ["type", "pieces", "vocab", "fallback", "special", "batch", "mask", "determinism", "budget", "embedding"],
      x: 560,
      y: 252,
      w: 270,
      h: 142,
      color: 0x304b6a
    }),
    node({
      id: "tokenizer_gauntlet_result",
      title: "Gauntlet Result",
      subtitle: "blocked until run",
      kind: "scalar",
      semanticName: "tokenizer_result",
      dtype: "bool",
      shape: "pass/fail",
      source: "contract terminal",
      consumer: "Chapter 2",
      sample: ["visible cases", "hidden cases", "determinism rerun"],
      x: 980,
      y: 270,
      w: 220,
      h: 110,
      color: 0x74491a
    })
  ],
  edges: [
    edge("e_c1_text_inspector", "raw_text_input", "text_inspector", "inspect"),
    edge("e_c1_raw_type_gate", "text_inspector", "type_gate", "utf8"),
    edge("e_c1_type_embedding_reject", "type_gate", "raw_embedding_probe", "reject", 0xf97316, "check"),
    edge("e_c1_text_tokenizer", "raw_text_input", "tokenizer_socket", "utf8 text"),
    edge("e_c1_tokenizer_pieces", "tokenizer_socket", "token_piece_stream", "pieces"),
    edge("e_c1_pieces_ids", "token_piece_stream", "token_id_emitter", "lookup"),
    edge("e_c1_ids_embedding", "token_id_emitter", "embedding_lookup_probe", "ids"),
    edge("e_c1_boundary_pieces", "boundary_cutter", "token_piece_stream", "pieces"),
    edge("e_c1_policy_meter", "split_policy_switch", "token_count_meter", "T count"),
    edge("e_c1_merge_meter", "merge_forge", "token_count_meter", "merged T"),
    edge("e_c1_symbols_lookup", "symbol_keeper", "vocab_lookup_gate", "preserved pieces"),
    edge("e_c1_vocab_lookup", "vocab_table", "vocab_lookup_gate", "rows"),
    edge("e_c1_lookup_ids", "vocab_lookup_gate", "token_id_emitter", "ids"),
    edge("e_c1_lookup_address", "vocab_lookup_gate", "address_lighting", "row"),
    edge("e_c1_address_embedding", "address_lighting", "embedding_lookup_probe", "row id"),
    edge("e_c1_stable_buffer", "stable_id_checker", "token_buffer", "stable ids"),
    edge("e_c1_buffer_oov", "vocab_lookup_gate", "oov_detector", "missing"),
    edge("e_c1_oov_fallback", "oov_detector", "fallback_splitter", "OOV"),
    edge("e_c1_fallback_special", "fallback_splitter", "special_token_injector", "resolved ids"),
    edge("e_c1_special_padding", "special_token_injector", "padding_builder", "special ids"),
    edge("e_c1_padding_mask", "padding_builder", "attention_mask_builder", "pad positions"),
    edge("e_c1_budget_buffer", "budget_gate", "token_buffer", "max T", 0xfbbf24, "check"),
    edge("e_c1_budget_gauntlet", "budget_gate", "tokenizer_contract_terminal", "budget trace", 0xfbbf24, "check"),
    edge("e_c1_cases_terminal", "gauntlet_cases", "tokenizer_contract_terminal", "test cases", 0x38bdf8, "check"),
    edge("e_c1_gauntlet_result", "tokenizer_contract_terminal", "tokenizer_gauntlet_result", "pass/fail", 0x22c55e, "check")
  ],
  repair: {
    kind: "tokenizer_pipeline",
    targetContract: "raw_text[B] -> token_ids[B,T] + attention_mask[B,T]",
    brokenMessage: "Raw text is still trying to enter numeric model modules without a tokenizer contract.",
    budget: { probes: 8, referenceRuns: 4 },
    tags,
    slots,
    probes,
    checks: [
      repairCheck("c1_1a_raw_text", "1-1A raw text object", "visible", ["c1_raw_text_object", "c1_text_inspector_open", "c1_not_numeric_tensor"], "raw text is inspectable but non-numeric", "Text intake contract is explicit.", "Raw text intake is incomplete.", "raw_text_input"),
      repairCheck("c1_1b_type_gate", "1-1B type gate failure", "visible", ["c1_type_gate_input", "c1_type_gate_failure", "c1_embedding_requires_ids"], "string input rejected at numeric port", "The required failure is observed.", "Type Gate failure has the wrong cause.", "type_gate"),
      repairCheck("c1_1c_tokenizer_socket", "1-1C tokenizer socket", "visible", ["c1_tokenizer_socket", "c1_tokenizer_input_contract", "c1_raw_bypass_blocked"], "raw text must pass through tokenizer", "Tokenizer Socket contract is installed.", "Tokenizer socket or bypass guard is missing.", "tokenizer_socket"),
      repairCheck("c1_1d_token_id", "1-1D token id contract", "visible", ["c1_token_id_output", "c1_token_id_rank", "c1_embedding_id_contract"], "token pieces become int ids", "Token id output can feed embedding lookup.", "Token id contract is incomplete.", "token_id_emitter"),
      repairCheck("c1_2a_boundary", "1-2A boundary cutter", "visible", ["c1_boundary_spaces", "c1_boundary_punctuation", "c1_boundary_order"], "spaces and punctuation create ordered pieces", "Boundary Cutter preserves visible order and punctuation.", "Boundary splitting is not faithful.", "boundary_cutter"),
      repairCheck("c1_2b_split_policy", "1-2B split comparison", "visible", ["c1_compare_char_policy", "c1_compare_word_policy", "c1_compare_subword_policy"], "subword policy selected after comparison", "Split policy tradeoffs are understood.", "Split policy comparison is incomplete.", "split_policy_switch"),
      repairCheck("c1_2c_count_meter", "1-2C token count meter", "visible", ["c1_count_meter_input", "c1_count_budget", "c1_count_fail_fast"], "token count enforces T <= 8", "Token Count Meter blocks overflow.", "Token budget is not enforced.", "token_count_meter"),
      repairCheck("c1_2d_merge", "1-2D merge forge", "visible", ["c1_merge_train_ing", "c1_merge_tokenizer_s", "c1_merge_count"], "merge rules reduce T deterministically", "Merge Forge is deterministic.", "Merge rules are missing or not counted.", "merge_forge"),
      repairCheck("c1_2e_symbols", "1-2E preserve symbols", "visible", ["c1_preserve_space_marker", "c1_preserve_punctuation", "c1_preserve_reversible_debug"], "symbols remain debuggable", "Symbol preservation is explicit.", "Symbols or decode debug data were dropped.", "symbol_keeper"),
      repairCheck("c1_3a_vocab_lookup", "1-3A vocab lookup", "visible", ["c1_lookup_vocab_rows", "c1_lookup_unknown_flag", "c1_lookup_emit_ids"], "each piece resolves to a row id or OOV", "Vocab lookup emits ids and flags missing pieces.", "Vocab lookup contract is incomplete.", "vocab_lookup_gate"),
      repairCheck("c1_3b_address", "1-3B address lighting", "visible", ["c1_address_piece_row", "c1_address_id_equals_row", "c1_address_embedding_probe"], "token id is a row address", "Address lighting proves id=row.", "Vocab ids are not tied to rows.", "address_lighting"),
      repairCheck("c1_3c_stable", "1-3C stable id test", "visible", ["c1_stable_same_piece", "c1_stable_repeat_run", "c1_stable_no_random_vocab"], "same input produces same ids", "Tokenizer id assignment is deterministic.", "Stable id contract failed.", "stable_id_checker"),
      repairCheck("c1_3d_buffer", "1-3D token buffer build", "visible", ["c1_buffer_axis_b", "c1_buffer_axis_t", "c1_buffer_rectangular"], "batch ids form int[B,T]", "Token Buffer has B/T axes and rectangular shape.", "Token Buffer shape contract is wrong.", "token_buffer"),
      repairCheck("c1_4a_oov", "1-4A OOV failure", "visible", ["c1_oov_detector", "c1_oov_block", "c1_oov_report"], "OOV is detected, blocked, and reported", "OOV failure is informative.", "OOV handling is not visible enough.", "oov_detector"),
      repairCheck("c1_4b_fallback", "1-4B fallback splitter", "visible", ["c1_fallback_subword", "c1_fallback_char", "c1_fallback_unk"], "fallback resolves rare pieces deterministically", "Fallback chain is complete.", "Fallback chain is incomplete.", "fallback_splitter"),
      repairCheck("c1_4c_special", "1-4C special token injector", "visible", ["c1_special_bos", "c1_special_eos", "c1_special_reserved"], "BOS/EOS/PAD/UNK are reserved", "Special token contract is correct.", "Special token contract is wrong.", "special_token_injector"),
      repairCheck("c1_4d_padding", "1-4D padding builder", "visible", ["c1_padding_side", "c1_padding_id", "c1_mask_matches_pad"], "right padding with matching mask", "Padding and attention mask agree.", "Padding or mask contract failed.", "padding_builder"),
      repairCheck("c1_4e_budget", "1-4E token budget gate", "visible", ["c1_budget_policy", "c1_budget_truncate", "c1_budget_trace"], "over-budget sequences cannot overflow", "Budget Gate handles overflow with trace.", "Budget Gate is incomplete.", "budget_gate"),
      repairCheck(
        "c1_behavior_pipeline",
        "pipeline contract",
        "behavior",
        ["c1_tokenizer_socket", "c1_lookup_emit_ids", "c1_fallback_unk", "c1_special_bos", "c1_padding_id", "c1_mask_matches_pad", "c1_buffer_rectangular"],
        "raw text -> ids[B,T] + mask[B,T]",
        "The full tokenizer pipeline contract is coherent.",
        "The pipeline still has a broken contract.",
        "tokenizer_contract_terminal",
        "Pipeline check is blocked until visible stages pass."
      ),
      repairCheck(
        "c1_reference_cases",
        "visible tokenizer cases",
        "reference",
        [
          "c1_gauntlet_type_contract",
          "c1_gauntlet_piece_contract",
          "c1_gauntlet_vocab_contract",
          "c1_gauntlet_fallback_contract",
          "c1_gauntlet_special_contract",
          "c1_gauntlet_batch_contract",
          "c1_gauntlet_mask_contract",
          "c1_gauntlet_determinism_contract",
          "c1_gauntlet_budget_contract",
          "c1_gauntlet_embedding_contract"
        ],
        "visible text set passes deterministic reference encode",
        "Visible tokenizer reference cases pass.",
        "Visible tokenizer cases failed.",
        "tokenizer_gauntlet_result",
        "Reference cases are blocked until the pipeline contract passes."
      ),
      repairCheck(
        "c1_hidden_cases",
        "hidden tokenizer cases",
        "hidden",
        [
          "c1_gauntlet_type_contract",
          "c1_gauntlet_piece_contract",
          "c1_gauntlet_vocab_contract",
          "c1_gauntlet_fallback_contract",
          "c1_gauntlet_special_contract",
          "c1_gauntlet_batch_contract",
          "c1_gauntlet_mask_contract",
          "c1_gauntlet_determinism_contract",
          "c1_gauntlet_budget_contract",
          "c1_gauntlet_embedding_contract"
        ],
        "hidden punctuation, OOV, padding, budget, and determinism cases pass",
        "Hidden tokenizer cases pass.",
        "Hidden tokenizer cases failed.",
        "tokenizer_gauntlet_result",
        "Hidden cases are blocked until the pipeline contract passes."
      )
    ],
    hiddenCases: hiddenTextSet,
    successSummary: "Chapter 1 tokenizer pipeline repaired: raw_text[B] -> token_ids[B,T] + attention_mask[B,T] with deterministic vocab ids and OOV handling."
  },
  traceSteps: [
    { id: "c1_step_text", title: "Raw Text", state: "warn", detail: "utf8 text cannot enter numeric modules", selectNodeId: "raw_text_input" },
    { id: "c1_step_split", title: "Split", state: "warn", detail: "Boundary Cutter and Merge Forge create ordered token pieces", selectNodeId: "boundary_cutter" },
    { id: "c1_step_vocab", title: "Vocab", state: "warn", detail: "pieces resolve to stable vocab row ids", selectNodeId: "vocab_lookup_gate" },
    { id: "c1_step_oov", title: "Fallback", state: "warn", detail: "OOV pieces are reported and resolved deterministically", selectNodeId: "fallback_splitter" },
    { id: "c1_step_buffer", title: "Buffer", state: "warn", detail: "ids are padded into token_ids[B,T] with attention_mask[B,T]", selectNodeId: "token_buffer" },
    { id: "c1_step_tests", title: "Gauntlet", state: "warn", detail: "visible and hidden tokenizer contracts must pass", selectNodeId: "tokenizer_gauntlet_result" }
  ]
};
