import type { BootcampLevel, CheckState, TensorNode } from "./workbenchTypes";

type NodeSpec = Omit<TensorNode, "stats" | "sample" | "checks"> & {
  stats?: TensorNode["stats"];
  sample?: string[];
  checks?: TensorNode["checks"];
};

const defaultStats = { min: "-", max: "-", mean: "-" };

function makeNode(spec: NodeSpec): TensorNode {
  return {
    ...spec,
    stats: spec.stats ?? defaultStats,
    sample: spec.sample ?? [],
    checks: spec.checks ?? [{ label: "inspectable", state: "pass", detail: "click to inspect shape, dtype, and sample values" }]
  };
}

function check(label: string, state: CheckState, detail: string) {
  return { label, state, detail };
}

export const broadcastAddLevel: BootcampLevel = {
  id: "0-4",
  title: "Broadcast Add",
  subtitle: "Repair the Broadcast Add Station",
  objective:
    "按 0-4A 到 0-4X 的阶梯挑战，从单格加法推进到 bias、position、mask 和 broadcast 陷阱调试，证明 broadcast add 合同可泛化。",
  sceneTitle: "Chapter 0-4 - Broadcast Add",
  sceneSubtitle:
    "Challenge ladder: Add Cell, same-shape add, broadcast rules, bias add, position add, mask add, trap debugger, and hidden gauntlet.",
  defaultSelectedNodeId: "add_gate_cell",
  briefing: [
    "Broadcast Add 不是随便相加，而是在每个输出 cell 上找到两个输入 cell 的对应来源再相加。",
    "小张量可以沿缺失轴或长度为 1 的轴逻辑复用，但 B/H/T/C/O 语义必须对齐。",
    "本关会把 add 从 scalar cell 扩展到 residual、bias、position embedding 和 attention mask。"
  ],
  knowledgeCards: [
    {
      title: "0-4 Broadcast Add",
      body:
        "你要修复 Broadcast Add Station。\n\n同 shape 的张量可以逐元素相加；小张量只有在 broadcast plan 合法且语义轴正确时，才能加到大张量上。",
      visual: ["Add Cell", "Same Shape", "Broadcast Rail", "Bias / Position / Mask", "Hidden Gauntlet"]
    },
    {
      title: "Broadcast 是逻辑视图",
      body:
        "缺失轴可以看成长度 1，长度为 1 的轴可以逻辑扩展。\n\n真正的 broadcast 通常不复制数据，只是在访问 cell 时复用同一个来源值。",
      visual: ["[C] -> [1,1,C]", "[T,C] -> [1,T,C]", "mask[1,1,T,T] -> [B,H,T,T]"]
    },
    {
      title: "语义比尺寸更重要",
      body:
        "Shape 能通过不代表操作正确。\n\n当 B、T、C 的数字刚好相等时，只有 axis semantics 和 Cell Trace 能证明 broadcast plan 是真的正确。",
      visual: ["hidden[4,4,4] + candidate[4]", "size says maybe", "trace decides"]
    }
  ],
  knowledgeTransition: {
    title: "Broadcast Debugger Bootcamp",
    body:
      "进入画布后，从 0-4A 开始。\n\n先修复一个加法 cell，再把同一个规则扩展到完整 tensor、broadcast plan 和 LLM 真实场景。",
    buttonLabel: "Start Broadcast Add"
  },
  mission: {
    title: "Repair Mission: Broadcast Add Ladder",
    body:
      "当前训练板会按 0-4A 到 0-4X 逐步打开。你需要证明自己理解 elementwise add、logical broadcast、axis alignment、mask add 和 semantic traps。",
    success: [
      "0-4A 到 0-4G 每个阶段都在画布上完成槽位修复。",
      "Cell Trace 能解释输出 cell 从哪些输入 cell 来。",
      "最终隐藏测试覆盖 bias、position、singleton、mask 和 equal-dimension trap。"
    ]
  },
  unlocks: ["Add Gate", "Broadcast Rail", "Ghost Expansion", "Cell Trace", "Bias Add", "Position Add", "Mask Add"],
  contracts: [
    "cell: scalar + scalar -> scalar",
    "same-shape: residual_a[B,T,C] + residual_b[B,T,C] -> hidden[B,T,C]",
    "broadcast: missing axes and singleton axes form a logical view",
    "bias: projected[B,T,O] + bias[O] -> projected[B,T,O]",
    "position: tok_emb[B,T,C] + pos_emb[T,C] -> hidden[B,T,C]",
    "mask: scores[B,H,Tq,Tk] + mask[1,1,Tq,Tk] -> masked_scores[B,H,Tq,Tk]"
  ],
  nodes: [
    makeNode({
      id: "scalar_a",
      title: "Scalar A",
      subtitle: "left cell",
      kind: "scalar",
      semanticName: "a",
      dtype: "float32",
      shape: "[]",
      source: "visible fixture",
      consumer: "add_gate_cell.left",
      stats: { min: "2.0", max: "2.0", mean: "2.0" },
      sample: ["A = 2.0", "negative case: -1.5"],
      checks: [check("numeric", "warn", "connect A into Add Gate")],
      x: 110,
      y: 244,
      w: 150,
      h: 76,
      color: 0x74491a
    }),
    makeNode({
      id: "scalar_b",
      title: "Scalar B",
      subtitle: "right cell",
      kind: "scalar",
      semanticName: "b",
      dtype: "float32",
      shape: "[]",
      source: "visible fixture",
      consumer: "add_gate_cell.right",
      stats: { min: "5.0", max: "5.0", mean: "5.0" },
      sample: ["B = 5.0", "negative case: 0.25"],
      checks: [check("numeric", "warn", "connect B into Add Gate")],
      x: 110,
      y: 418,
      w: 150,
      h: 76,
      color: 0x74491a
    }),
    makeNode({
      id: "add_gate_cell",
      title: "Add Gate",
      subtitle: "cell inputs open",
      kind: "operation",
      semanticName: "add",
      dtype: "op",
      shape: "[] + []",
      source: "Scalar A, Scalar B",
      consumer: "output cell",
      sample: ["out = A + B", "2.0 + 5.0 = 7.0"],
      checks: [check("inputs", "warn", "both numeric inputs are required")],
      x: 478,
      y: 326,
      w: 194,
      h: 98,
      color: 0x304b6a
    }),
    makeNode({
      id: "output_cell",
      title: "Output Cell",
      subtitle: "waiting for trace",
      kind: "scalar",
      semanticName: "out",
      dtype: "float32",
      shape: "[]",
      source: "add_gate_cell",
      consumer: "cell trace",
      stats: { min: "7.0", max: "7.0", mean: "7.0" },
      sample: ["expected: 7.0", "must be computed, not typed manually"],
      checks: [check("reference", "warn", "run cell trace")],
      x: 854,
      y: 326,
      w: 182,
      h: 96,
      color: 0x236998
    }),
    makeNode({
      id: "cell_trace",
      title: "Cell Trace",
      subtitle: "source proof",
      kind: "operation",
      semanticName: "cell_trace",
      dtype: "tool",
      shape: "out[]",
      source: "output cell",
      consumer: "stage gate",
      sample: ["out[] <- A[] + B[]", "7.0 exact match"],
      checks: [check("trace", "warn", "prove output source cells")],
      x: 1094,
      y: 326,
      w: 186,
      h: 96,
      color: 0x304b6a
    }),
    makeNode({
      id: "same_a",
      title: "Residual A",
      subtitle: "same shape input",
      kind: "matrix",
      semanticName: "residual_a",
      dtype: "float32",
      shape: "[T,C]",
      source: "residual stream",
      consumer: "same_add_gate.left",
      stats: { min: "1", max: "6", mean: "3.5" },
      sample: ["[[1,2,3],[4,5,6]]", "axes: T,C"],
      checks: [check("shape", "warn", "align with Residual B")],
      x: 108,
      y: 238,
      w: 218,
      h: 124,
      color: 0x24608a
    }),
    makeNode({
      id: "same_b",
      title: "Residual B",
      subtitle: "same shape input",
      kind: "matrix",
      semanticName: "residual_b",
      dtype: "float32",
      shape: "[T,C]",
      source: "module branch",
      consumer: "same_add_gate.right",
      stats: { min: "10", max: "60", mean: "35" },
      sample: ["[[10,20,30],[40,50,60]]", "axes: T,C"],
      checks: [check("shape", "warn", "must match Residual A")],
      x: 108,
      y: 430,
      w: 218,
      h: 124,
      color: 0x24608a
    }),
    makeNode({
      id: "same_add_gate",
      title: "Tensor Add Grid",
      subtitle: "same-shape gate",
      kind: "operation",
      semanticName: "same_shape_add",
      dtype: "op",
      shape: "[T,C]+[T,C]",
      source: "Residual A, Residual B",
      consumer: "same_out",
      sample: ["out[t,c] = A[t,c] + B[t,c]", "shape remains [T,C]"],
      checks: [check("same shape", "warn", "pair cells by identical coordinates")],
      x: 504,
      y: 334,
      w: 220,
      h: 102,
      color: 0x304b6a
    }),
    makeNode({
      id: "same_out",
      title: "Same-Shape Output",
      subtitle: "waiting",
      kind: "matrix",
      semanticName: "residual_sum",
      dtype: "float32",
      shape: "[T,C]",
      source: "same_add_gate",
      consumer: "reference checker",
      stats: { min: "11", max: "66", mean: "38.5" },
      sample: ["[[11,22,33],[44,55,66]]", "same T/C axes"],
      checks: [check("output", "warn", "output shape and values must match")],
      x: 906,
      y: 304,
      w: 238,
      h: 138,
      color: 0x236998
    }),
    makeNode({
      id: "same_trace",
      title: "Grid Trace",
      subtitle: "cell provenance",
      kind: "operation",
      semanticName: "grid_trace",
      dtype: "tool",
      shape: "out[t,c]",
      source: "same_out",
      consumer: "stage gate",
      sample: ["out[1,2] = 6 + 60", "no axis swap"],
      checks: [check("trace", "warn", "trace a matching output cell")],
      x: 1170,
      y: 324,
      w: 190,
      h: 104,
      color: 0x304b6a
    }),
    makeNode({
      id: "target_btc",
      title: "Target Tensor",
      subtitle: "broadcast target",
      kind: "tensor",
      semanticName: "target",
      dtype: "float32",
      shape: "[B,T,C]",
      source: "hidden fixture",
      consumer: "broadcast_rail_lab",
      stats: { min: "-0.6", max: "0.8", mean: "0.02" },
      sample: ["target: [B][T][C]", "visible: [2,3,4]"],
      checks: [check("target", "pass", "rank 3 target is fixed")],
      x: 92,
      y: 204,
      w: 220,
      h: 128,
      color: 0x24608a
    }),
    makeNode({
      id: "vector_c",
      title: "Vector Case",
      subtitle: "[C] input",
      kind: "parameter",
      semanticName: "bias_like",
      dtype: "float32",
      shape: "[C]",
      source: "case A",
      consumer: "broadcast_rail_lab",
      stats: { min: "0.1", max: "0.4", mean: "0.25" },
      sample: ["view: [1,1,C]", "expands over B/T"],
      checks: [check("case A", "warn", "right-align under C")],
      x: 116,
      y: 430,
      w: 178,
      h: 84,
      color: 0x5a4c8f
    }),
    makeNode({
      id: "matrix_tc",
      title: "Matrix Case",
      subtitle: "[T,C] input",
      kind: "matrix",
      semanticName: "position_like",
      dtype: "float32",
      shape: "[T,C]",
      source: "case B",
      consumer: "broadcast_rail_lab",
      stats: { min: "-0.1", max: "0.1", mean: "0.0" },
      sample: ["view: [1,T,C]", "expands over B"],
      checks: [check("case B", "warn", "missing B axis is logical")],
      x: 346,
      y: 430,
      w: 190,
      h: 84,
      color: 0x5a4c8f
    }),
    makeNode({
      id: "singleton_scale",
      title: "Singleton Case",
      subtitle: "[1,T,1] input",
      kind: "tensor",
      semanticName: "scale",
      dtype: "float32",
      shape: "[1,T,1]",
      source: "case C",
      consumer: "broadcast_rail_lab",
      stats: { min: "-0.2", max: "0.2", mean: "0.0" },
      sample: ["B and C axes expand", "T axis stays aligned"],
      checks: [check("case C", "warn", "expand singleton axes")],
      x: 574,
      y: 430,
      w: 190,
      h: 84,
      color: 0x5a4c8f
    }),
    makeNode({
      id: "broadcast_rail_lab",
      title: "Broadcast Rail",
      subtitle: "plan incomplete",
      kind: "operation",
      semanticName: "broadcast_plan",
      dtype: "rule",
      shape: "[B][T][C]",
      source: "target + small tensors",
      consumer: "ghost_expansion",
      sample: ["Input [C] -> [*][*][C]", "Input [T,C] -> [*][T][C]"],
      checks: [check("plan", "warn", "build missing-axis and singleton-axis plans")],
      x: 834,
      y: 318,
      w: 236,
      h: 118,
      color: 0x304b6a
    }),
    makeNode({
      id: "ghost_expansion",
      title: "Ghost Expansion",
      subtitle: "logical view",
      kind: "operation",
      semanticName: "broadcast_view",
      dtype: "tool",
      shape: "no-copy",
      source: "broadcast_rail_lab",
      consumer: "plan_checker",
      sample: ["real storage remains small", "ghost copies are logical"],
      checks: [check("memory", "warn", "use logical broadcast view")],
      x: 1128,
      y: 214,
      w: 210,
      h: 100,
      color: 0x304b6a
    }),
    makeNode({
      id: "plan_checker",
      title: "Plan Checker",
      subtitle: "3 cases",
      kind: "scalar",
      semanticName: "broadcast_tests",
      dtype: "bool",
      shape: "A/B/C",
      source: "broadcast plans",
      consumer: "stage gate",
      sample: ["Case A [C]", "Case B [T,C]", "Case C [1,T,1]"],
      checks: [check("validity", "warn", "shape, semantic, and sample trace must pass")],
      x: 1128,
      y: 390,
      w: 210,
      h: 100,
      color: 0x74491a
    }),
    makeNode({
      id: "projected_bto",
      title: "Projected",
      subtitle: "Linear output",
      kind: "tensor",
      semanticName: "projected",
      dtype: "float32",
      shape: "[B,T,O]",
      source: "0-2 Linear",
      consumer: "bias_add_gate.left",
      stats: { min: "1.0", max: "6.0", mean: "3.5" },
      sample: ["visible: [1,2,3]", "O is output feature axis"],
      checks: [check("target", "pass", "bias target uses O axis")],
      x: 116,
      y: 282,
      w: 230,
      h: 132,
      color: 0x24608a
    }),
    makeNode({
      id: "bias_o",
      title: "Bias Strip",
      subtitle: "channel offsets",
      kind: "parameter",
      semanticName: "bias",
      dtype: "float32",
      shape: "[O]",
      source: "Linear parameter",
      consumer: "bias_rail",
      stats: { min: "0.1", max: "0.3", mean: "0.2" },
      sample: ["bias[O=3] = [0.1,0.2,0.3]", "reuse for every B,T"],
      checks: [check("axis", "warn", "align to O only")],
      x: 432,
      y: 438,
      w: 196,
      h: 84,
      color: 0x5a4c8f
    }),
    makeNode({
      id: "bias_rail",
      title: "Bias Broadcast Rail",
      subtitle: "O axis not mounted",
      kind: "operation",
      semanticName: "bias_broadcast",
      dtype: "rule",
      shape: "[B,T,O] + [O]",
      source: "projected, bias",
      consumer: "bias_add_gate",
      sample: ["bias view: [1,1,O]", "expand over B and T"],
      checks: [check("rail", "warn", "mount bias on O axis")],
      x: 688,
      y: 326,
      w: 236,
      h: 108,
      color: 0x304b6a
    }),
    makeNode({
      id: "bias_add_gate",
      title: "Broadcast Add Gate",
      subtitle: "bias add",
      kind: "operation",
      semanticName: "bias_add",
      dtype: "op",
      shape: "[B,T,O]+[1,1,O]",
      source: "projected, bias rail",
      consumer: "bias_out",
      sample: ["out[b,t,o] = projected[b,t,o] + bias[o]"],
      checks: [check("operation", "warn", "additive broadcast only")],
      x: 968,
      y: 326,
      w: 224,
      h: 108,
      color: 0x304b6a
    }),
    makeNode({
      id: "bias_out",
      title: "Bias Output",
      subtitle: "waiting",
      kind: "tensor",
      semanticName: "projected_with_bias",
      dtype: "float32",
      shape: "[B,T,O]",
      source: "bias_add_gate",
      consumer: "bias_reference",
      stats: { min: "1.1", max: "6.3", mean: "3.7" },
      sample: ["[[1.1,2.2,3.3],[4.1,5.2,6.3]]"],
      checks: [check("reference", "warn", "compare against bias reference")],
      x: 1228,
      y: 300,
      w: 220,
      h: 126,
      color: 0x236998
    }),
    makeNode({
      id: "bias_reference",
      title: "Reference Checker",
      subtitle: "allclose",
      kind: "scalar",
      semanticName: "max_error",
      dtype: "float32",
      shape: "<= 1e-5",
      source: "bias_out",
      consumer: "stage gate",
      sample: ["cell trace: out[0,1,2] = 6 + 0.3"],
      checks: [check("allclose", "warn", "shape and numbers must match")],
      x: 1228,
      y: 478,
      w: 220,
      h: 96,
      color: 0x74491a
    }),
    makeNode({
      id: "tok_emb",
      title: "Token Embedding",
      subtitle: "base activation",
      kind: "tensor",
      semanticName: "tok_emb",
      dtype: "float32",
      shape: "[B,T,C]",
      source: "embedding lookup",
      consumer: "position_add_gate.left",
      stats: { min: "-0.4", max: "0.5", mean: "0.01" },
      sample: ["token vectors do not know position yet", "visible: [2,3,2]"],
      checks: [check("target", "pass", "position add target")],
      x: 104,
      y: 286,
      w: 236,
      h: 132,
      color: 0x24608a
    }),
    makeNode({
      id: "pos_sheet",
      title: "Position Sheet",
      subtitle: "T by C",
      kind: "matrix",
      semanticName: "pos_emb",
      dtype: "float32",
      shape: "[T,C]",
      source: "position table",
      consumer: "position_rail",
      stats: { min: "-0.06", max: "0.07", mean: "0.0" },
      sample: ["one C vector per token position", "same t reused for all B"],
      checks: [check("axis", "warn", "align both T and C")],
      x: 434,
      y: 438,
      w: 210,
      h: 88,
      color: 0x5a4c8f
    }),
    makeNode({
      id: "position_rail",
      title: "Position Rail",
      subtitle: "T/C not locked",
      kind: "operation",
      semanticName: "position_broadcast",
      dtype: "rule",
      shape: "[B,T,C] + [T,C]",
      source: "tok_emb, pos_sheet",
      consumer: "position_add_gate",
      sample: ["pos view: [1,T,C]", "B axis is broadcasted"],
      checks: [check("rail", "warn", "do not collapse pos_emb into bias[C]")],
      x: 716,
      y: 328,
      w: 236,
      h: 108,
      color: 0x304b6a
    }),
    makeNode({
      id: "position_add_gate",
      title: "Position Add Gate",
      subtitle: "position add",
      kind: "operation",
      semanticName: "position_add",
      dtype: "op",
      shape: "[B,T,C]+[1,T,C]",
      source: "tok_emb, position_rail",
      consumer: "hidden_out",
      sample: ["hidden[b,t,c] = tok_emb[b,t,c] + pos_emb[t,c]"],
      checks: [check("operation", "warn", "preserve token-position variation")],
      x: 994,
      y: 328,
      w: 230,
      h: 108,
      color: 0x304b6a
    }),
    makeNode({
      id: "hidden_out",
      title: "Hidden Tensor",
      subtitle: "waiting",
      kind: "tensor",
      semanticName: "hidden",
      dtype: "float32",
      shape: "[B,T,C]",
      source: "position_add_gate",
      consumer: "position_trace",
      stats: { min: "-0.45", max: "0.57", mean: "0.02" },
      sample: ["same pos_emb[t,:] reused across batch", "T variation preserved"],
      checks: [check("output", "warn", "output shape remains [B,T,C]")],
      x: 1262,
      y: 306,
      w: 220,
      h: 126,
      color: 0x236998
    }),
    makeNode({
      id: "position_trace",
      title: "Position Trace",
      subtitle: "not bias",
      kind: "operation",
      semanticName: "position_trace",
      dtype: "tool",
      shape: "hidden[b,t,c]",
      source: "hidden_out",
      consumer: "stage gate",
      sample: ["hidden[0,2,:] and hidden[1,2,:] reuse pos_emb[2,:]", "pos_emb is not bias[C]"],
      checks: [check("trace", "warn", "prove T axis is retained")],
      x: 1262,
      y: 480,
      w: 220,
      h: 100,
      color: 0x304b6a
    }),
    makeNode({
      id: "scores_tensor",
      title: "Attention Scores",
      subtitle: "from 0-3 QK^T",
      kind: "attention",
      semanticName: "scores",
      dtype: "float32",
      shape: "[B,H,Tq,Tk]",
      source: "QK^T / sqrt(D)",
      consumer: "mask_add_gate.left",
      stats: { min: "-2.1", max: "2.3", mean: "0.04" },
      sample: ["visible: [2,2,4,4]", "rows=query token, cols=key token"],
      checks: [check("score axes", "pass", "two T axes have different roles")],
      x: 100,
      y: 262,
      w: 246,
      h: 146,
      color: 0x1b6f78
    }),
    makeNode({
      id: "mask_plate",
      title: "Mask Plate",
      subtitle: "causal pattern",
      kind: "mask",
      semanticName: "causal_mask",
      dtype: "float32",
      shape: "[1,1,Tq,Tk]",
      source: "tril rule",
      consumer: "mask_rail",
      stats: { min: "-1e9", max: "0", mean: "-3.75e8" },
      sample: ["0 if k <= q", "-1e9 if k > q"],
      checks: [check("mask value", "warn", "add mask before softmax")],
      x: 432,
      y: 446,
      w: 212,
      h: 94,
      color: 0x344358
    }),
    makeNode({
      id: "mask_rail",
      title: "Mask Broadcast Rail",
      subtitle: "Tq/Tk not locked",
      kind: "operation",
      semanticName: "mask_broadcast",
      dtype: "rule",
      shape: "[B,H,Tq,Tk] + [1,1,Tq,Tk]",
      source: "scores, mask plate",
      consumer: "mask_add_gate",
      sample: ["B/H singleton axes expand", "Tq/Tk must not swap"],
      checks: [check("rail", "warn", "align query and key axes")],
      x: 730,
      y: 326,
      w: 248,
      h: 114,
      color: 0x304b6a
    }),
    makeNode({
      id: "mask_add_gate",
      title: "Mask Add Gate",
      subtitle: "additive mask",
      kind: "operation",
      semanticName: "mask_add",
      dtype: "op",
      shape: "scores + mask",
      source: "scores, mask rail",
      consumer: "masked_scores",
      sample: ["masked[b,h,q,k] = scores[b,h,q,k] + mask[0,0,q,k]", "not multiplication mask"],
      checks: [check("operation", "warn", "must be additive before softmax")],
      x: 1026,
      y: 326,
      w: 230,
      h: 112,
      color: 0x304b6a
    }),
    makeNode({
      id: "masked_scores",
      title: "Masked Scores",
      subtitle: "waiting",
      kind: "attention",
      semanticName: "masked_scores",
      dtype: "float32",
      shape: "[B,H,Tq,Tk]",
      source: "mask_add_gate",
      consumer: "illegal_cell_checker",
      stats: { min: "-1e9", max: "2.3", mean: "-3.75e8" },
      sample: ["future cells receive a large negative value", "legal cells keep scores"],
      checks: [check("output", "warn", "illegal future cells must be blocked")],
      x: 1294,
      y: 274,
      w: 238,
      h: 142,
      color: 0x1b6f78
    }),
    makeNode({
      id: "illegal_cell_checker",
      title: "Illegal Cell Checker",
      subtitle: "future-token probe",
      kind: "scalar",
      semanticName: "illegal_attention",
      dtype: "bool",
      shape: "cell[q,k]",
      source: "masked_scores",
      consumer: "stage gate",
      sample: ["cell q=2,k=3 must be very negative", "orientation decides future direction"],
      checks: [check("future cell", "warn", "trace one illegal attention cell")],
      x: 1294,
      y: 478,
      w: 238,
      h: 104,
      color: 0x74491a
    }),
    makeNode({
      id: "trap_cases",
      title: "Broadcast Trap Cases",
      subtitle: "mixed failures",
      kind: "tensor",
      semanticName: "trap_cases",
      dtype: "debug",
      shape: "3 boards",
      source: "saved faulty circuits",
      consumer: "trap_inspector",
      sample: ["A: [T] right-aligns to C", "B: [B,C] shape-valid trap", "C: pos_emb as bias"],
      checks: [check("cases", "warn", "diagnose each trap type")],
      x: 106,
      y: 284,
      w: 244,
      h: 142,
      color: 0x74491a
    }),
    makeNode({
      id: "trap_inspector",
      title: "Trap Inspector",
      subtitle: "rank -> axis -> trace",
      kind: "operation",
      semanticName: "broadcast_debugger",
      dtype: "tool",
      shape: "debug plan",
      source: "trap cases",
      consumer: "semantic_warning",
      sample: ["check rank", "check axis alignment", "trace output cell"],
      checks: [check("debug order", "warn", "do not patch by shape alone")],
      x: 452,
      y: 298,
      w: 240,
      h: 118,
      color: 0x304b6a
    }),
    makeNode({
      id: "semantic_warning",
      title: "Semantic Warning Lens",
      subtitle: "shape may pass",
      kind: "operation",
      semanticName: "semantic_warning",
      dtype: "tool",
      shape: "shape-valid?",
      source: "trap inspector",
      consumer: "trace_probe_04",
      sample: ["yellow = raw broadcast valid but semantic risk", "red = impossible broadcast"],
      checks: [check("warning", "warn", "separate shape errors from semantic errors")],
      x: 766,
      y: 298,
      w: 248,
      h: 118,
      color: 0x304b6a
    }),
    makeNode({
      id: "trace_probe_04",
      title: "Cell Trace Probe",
      subtitle: "truth source",
      kind: "operation",
      semanticName: "cell_trace",
      dtype: "tool",
      shape: "out index -> input index",
      source: "semantic warning lens",
      consumer: "trap_patch",
      sample: ["out[b,t,c] should use pos[t,c], not pos[c]", "equal sizes cannot decide semantics"],
      checks: [check("trace", "warn", "trace suspicious cell")],
      x: 1078,
      y: 298,
      w: 240,
      h: 118,
      color: 0x304b6a
    }),
    makeNode({
      id: "trap_patch",
      title: "Repair Patch",
      subtitle: "waiting",
      kind: "operation",
      semanticName: "broadcast_patch",
      dtype: "rule",
      shape: "4 fixes",
      source: "trace probe",
      consumer: "trap_reference_04",
      sample: ["right-align safely", "reject B/T swaps", "keep pos T", "avoid materialized repeat"],
      checks: [check("patch", "warn", "record all trap fixes")],
      x: 1380,
      y: 298,
      w: 224,
      h: 118,
      color: 0x304b6a
    }),
    makeNode({
      id: "trap_reference_04",
      title: "Trap Reference",
      subtitle: "debug allclose",
      kind: "scalar",
      semanticName: "trap_reference",
      dtype: "bool",
      shape: "all cases",
      source: "trap patch",
      consumer: "gauntlet",
      sample: ["semantic-invalid cases rejected", "logical broadcast accepted"],
      checks: [check("reference", "warn", "patched circuits must match reference")],
      x: 1380,
      y: 478,
      w: 224,
      h: 96,
      color: 0x74491a
    }),
    makeNode({
      id: "broadcast_gauntlet_cases",
      title: "Broadcast Gauntlet",
      subtitle: "hidden cases",
      kind: "tensor",
      semanticName: "hidden_cases",
      dtype: "test",
      shape: "6 cases",
      source: "autograder",
      consumer: "broadcast_contract_terminal",
      sample: ["bias add", "position add", "singleton", "mask", "equal-dim trap", "semantic trace"],
      checks: [check("cases", "warn", "arm every hidden broadcast case")],
      x: 120,
      y: 308,
      w: 260,
      h: 126,
      color: 0x74491a
    }),
    makeNode({
      id: "broadcast_contract_terminal",
      title: "Broadcast Contract",
      subtitle: "general rule",
      kind: "operation",
      semanticName: "broadcast_contract",
      dtype: "rule",
      shape: "shape + semantics",
      source: "gauntlet cases",
      consumer: "hidden_broadcast_reference",
      sample: ["rank", "axis alignment", "singleton/missing axes", "cell trace"],
      checks: [check("contract", "warn", "prove the full rule, not memorized shapes")],
      x: 520,
      y: 308,
      w: 260,
      h: 126,
      color: 0x304b6a
    }),
    makeNode({
      id: "hidden_broadcast_reference",
      title: "Hidden Reference",
      subtitle: "allclose + semantic",
      kind: "scalar",
      semanticName: "hidden_reference",
      dtype: "bool",
      shape: "max_error <= 1e-5",
      source: "contract terminal",
      consumer: "broadcast_gauntlet_result",
      sample: ["hidden[4,4,4] + candidate[4]", "scores[B,H,T,T] + mask"],
      checks: [check("reference", "warn", "hidden reference catches equal-size traps")],
      x: 918,
      y: 308,
      w: 260,
      h: 126,
      color: 0x74491a
    }),
    makeNode({
      id: "broadcast_gauntlet_result",
      title: "Gauntlet Result",
      subtitle: "run final tests",
      kind: "scalar",
      semanticName: "broadcast_pass",
      dtype: "bool",
      shape: "A/B/C/D/E/F",
      source: "hidden reference",
      consumer: "chapter unlock",
      sample: ["all main 0-4 contracts pass", "logical broadcast eligible for A rank"],
      checks: [check("hidden tests", "warn", "complete final broadcast test setup")],
      x: 1308,
      y: 308,
      w: 238,
      h: 126,
      color: 0x74491a
    })
  ],
  edges: [
    { id: "e_04a_a_gate", from: "scalar_a", to: "add_gate_cell", label: "A[]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04a_b_gate", from: "scalar_b", to: "add_gate_cell", label: "B[]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04a_gate_out", from: "add_gate_cell", to: "output_cell", label: "A+B", color: 0x22c55e, flow: "forward" },
    { id: "e_04a_out_trace", from: "output_cell", to: "cell_trace", label: "cell source", color: 0xfbbf24, flow: "check" },
    { id: "e_04b_a_gate", from: "same_a", to: "same_add_gate", label: "A[T,C]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04b_b_gate", from: "same_b", to: "same_add_gate", label: "B[T,C]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04b_gate_out", from: "same_add_gate", to: "same_out", label: "out[T,C]", color: 0x22c55e, flow: "forward" },
    { id: "e_04b_out_trace", from: "same_out", to: "same_trace", label: "grid trace", color: 0xfbbf24, flow: "check" },
    { id: "e_04c_target_rail", from: "target_btc", to: "broadcast_rail_lab", label: "target[B,T,C]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04c_vector_rail", from: "vector_c", to: "broadcast_rail_lab", label: "[C]", color: 0xc4b5fd, flow: "parameter" },
    { id: "e_04c_matrix_rail", from: "matrix_tc", to: "broadcast_rail_lab", label: "[T,C]", color: 0xc4b5fd, flow: "parameter" },
    { id: "e_04c_singleton_rail", from: "singleton_scale", to: "broadcast_rail_lab", label: "[1,T,1]", color: 0xc4b5fd, flow: "parameter" },
    { id: "e_04c_rail_ghost", from: "broadcast_rail_lab", to: "ghost_expansion", label: "logical view", color: 0x22c55e, flow: "check" },
    { id: "e_04c_rail_plan", from: "broadcast_rail_lab", to: "plan_checker", label: "plan tests", color: 0xfbbf24, flow: "check" },
    { id: "e_04d_projected_rail", from: "projected_bto", to: "bias_rail", label: "projected[B,T,O]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04d_bias_rail", from: "bias_o", to: "bias_rail", label: "bias[O]", color: 0xc4b5fd, flow: "parameter" },
    { id: "e_04d_rail_gate", from: "bias_rail", to: "bias_add_gate", label: "view[1,1,O]", color: 0x22c55e, flow: "check" },
    { id: "e_04d_gate_out", from: "bias_add_gate", to: "bias_out", label: "out[B,T,O]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04d_out_ref", from: "bias_out", to: "bias_reference", label: "allclose", color: 0xfbbf24, flow: "check" },
    { id: "e_04e_tok_rail", from: "tok_emb", to: "position_rail", label: "tok_emb[B,T,C]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04e_pos_rail", from: "pos_sheet", to: "position_rail", label: "pos_emb[T,C]", color: 0xc4b5fd, flow: "parameter" },
    { id: "e_04e_rail_gate", from: "position_rail", to: "position_add_gate", label: "view[1,T,C]", color: 0x22c55e, flow: "check" },
    { id: "e_04e_gate_hidden", from: "position_add_gate", to: "hidden_out", label: "hidden[B,T,C]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04e_hidden_trace", from: "hidden_out", to: "position_trace", label: "cell trace", color: 0xfbbf24, flow: "check" },
    { id: "e_04f_scores_rail", from: "scores_tensor", to: "mask_rail", label: "scores[B,H,Tq,Tk]", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04f_mask_rail", from: "mask_plate", to: "mask_rail", label: "mask[1,1,Tq,Tk]", color: 0x94a3b8, flow: "mask" },
    { id: "e_04f_rail_gate", from: "mask_rail", to: "mask_add_gate", label: "view[B,H,Tq,Tk]", color: 0x22c55e, flow: "check" },
    { id: "e_04f_gate_masked", from: "mask_add_gate", to: "masked_scores", label: "masked scores", color: 0x7dd3fc, flow: "forward" },
    { id: "e_04f_masked_check", from: "masked_scores", to: "illegal_cell_checker", label: "future cell", color: 0xfbbf24, flow: "check" },
    { id: "e_04g_cases_inspector", from: "trap_cases", to: "trap_inspector", label: "fault set", color: 0xfbbf24, flow: "check" },
    { id: "e_04g_inspector_warning", from: "trap_inspector", to: "semantic_warning", label: "shape vs semantic", color: 0xfbbf24, flow: "check" },
    { id: "e_04g_warning_trace", from: "semantic_warning", to: "trace_probe_04", label: "cell source", color: 0x7dd3fc, flow: "check" },
    { id: "e_04g_trace_patch", from: "trace_probe_04", to: "trap_patch", label: "repair rules", color: 0x22c55e, flow: "check" },
    { id: "e_04g_patch_ref", from: "trap_patch", to: "trap_reference_04", label: "reference", color: 0xfbbf24, flow: "check" },
    { id: "e_04x_cases_contract", from: "broadcast_gauntlet_cases", to: "broadcast_contract_terminal", label: "6 hidden cases", color: 0xfbbf24, flow: "check" },
    { id: "e_04x_contract_ref", from: "broadcast_contract_terminal", to: "hidden_broadcast_reference", label: "allclose + semantic", color: 0x22c55e, flow: "check" },
    { id: "e_04x_ref_result", from: "hidden_broadcast_reference", to: "broadcast_gauntlet_result", label: "pass/fail", color: 0xfbbf24, flow: "check" }
  ],
  repair: {
    kind: "broadcast_rail",
    targetContract:
      "elementwise add, same-shape add, broadcast view, bias add, position add, mask add, semantic traps, and hidden broadcast gauntlet",
    brokenMessage:
      "Broadcast Add Station incomplete: Add Gate inputs, axis alignment, logical broadcast views, LLM-specific bias/position/mask plans, and semantic traps must all pass.",
    budget: { probes: 10, referenceRuns: 5 },
    tags: [
      { id: "wire_scalar_a", label: "Connect Scalar A", shortLabel: "A[]", detail: "feed Scalar A into the left Add input", category: "data" },
      { id: "wire_scalar_b", label: "Connect Scalar B", shortLabel: "B[]", detail: "feed Scalar B into the right Add input", category: "data" },
      { id: "manual_output", label: "Manual Output", shortLabel: "typed", detail: "wrong: output must be computed", category: "operation" },
      { id: "cell_trace_exact", label: "Cell Trace Exact", shortLabel: "trace", detail: "prove 2.0 + 5.0 = 7.0", category: "operation" },
      { id: "same_shape_tc", label: "Match [T,C]", shortLabel: "[T,C]", detail: "both inputs share T and C axes", category: "contract" },
      { id: "same_shape_ct", label: "Swap to [C,T]", shortLabel: "[C,T]", detail: "wrong: cells would be transposed", category: "contract" },
      { id: "same_output_tc", label: "Output [T,C]", shortLabel: "out[T,C]", detail: "same-shape add preserves shape", category: "contract" },
      { id: "same_trace_cell", label: "Trace same cell", shortLabel: "cell", detail: "out[t,c] uses A[t,c] and B[t,c]", category: "operation" },
      { id: "align_c_right", label: "Right-align [C]", shortLabel: "[C]->C", detail: "[C] becomes [1,1,C]", category: "rail" },
      { id: "align_c_to_t", label: "Align [C] to T", shortLabel: "[C]->T", detail: "wrong for channel-style broadcast", category: "rail" },
      { id: "insert_missing_b", label: "Insert missing B", shortLabel: "*B", detail: "[T,C] becomes [1,T,C]", category: "rank" },
      { id: "insert_missing_c", label: "Insert missing C", shortLabel: "*C", detail: "wrong: [T,C] must keep C", category: "rank" },
      { id: "expand_singleton_bt", label: "Expand singleton axes", shortLabel: "1->*", detail: "[1,T,1] expands over B and C", category: "rank" },
      { id: "materialized_repeat", label: "Materialized Repeat", shortLabel: "repeat", detail: "correct values but inefficient real copies", category: "operation" },
      { id: "logical_view", label: "Logical Broadcast View", shortLabel: "view", detail: "reuse values without real copies", category: "operation" },
      { id: "axis_o", label: "Output axis O", shortLabel: "O", detail: "Linear bias belongs to output feature axis", category: "axis" },
      { id: "axis_t", label: "Token axis T", shortLabel: "T", detail: "wrong axis for Linear bias", category: "axis" },
      { id: "expand_bt", label: "Broadcast over B/T", shortLabel: "*B/*T", detail: "bias is reused for every sample and token", category: "rank" },
      { id: "bias_cell_trace", label: "Trace bias cell", shortLabel: "trace", detail: "out[b,t,o] uses bias[o]", category: "operation" },
      { id: "align_tc", label: "Align [T,C]", shortLabel: "[T,C]", detail: "position embedding owns token and channel axes", category: "axis" },
      { id: "align_c_only", label: "Align [C] only", shortLabel: "[C]", detail: "wrong for position embedding; this becomes bias", category: "axis" },
      { id: "broadcast_b", label: "Broadcast over B", shortLabel: "*B", detail: "same pos sheet is used for every batch sample", category: "rank" },
      { id: "preserve_position_t", label: "Preserve T variation", shortLabel: "keep T", detail: "pos_emb must vary by token position", category: "semantic" },
      { id: "align_tqtk", label: "Align Tq/Tk", shortLabel: "Tq/Tk", detail: "mask row/column axes match score row/column axes", category: "axis" },
      { id: "swap_tqtk", label: "Swap Tq/Tk", shortLabel: "swap", detail: "wrong: future-token direction flips", category: "axis" },
      { id: "expand_bh", label: "Broadcast over B/H", shortLabel: "*B/*H", detail: "mask singleton axes expand over batch and head", category: "rank" },
      { id: "add_negative_mask", label: "Add negative mask", shortLabel: "+mask", detail: "use additive -1e9 mask before softmax", category: "operation" },
      { id: "multiply_mask", label: "Multiply mask", shortLabel: "*mask", detail: "wrong for this stage; expected additive mask", category: "operation" },
      { id: "mask_cell_trace", label: "Trace illegal cell", shortLabel: "cell", detail: "future cell receives -1e9", category: "operation" },
      { id: "debug_right_align", label: "Check right alignment", shortLabel: "right", detail: "raw broadcast aligns trailing axes first", category: "operation" },
      { id: "debug_bt_swap", label: "Catch B/T swap", shortLabel: "B/T", detail: "equal sizes cannot justify swapping semantics", category: "semantic" },
      { id: "debug_pos_bias", label: "Catch pos-as-bias", shortLabel: "pos!=bias", detail: "pos_emb[T,C] must not collapse into bias[C]", category: "semantic" },
      { id: "debug_no_repeat", label: "Prefer broadcast view", shortLabel: "no repeat", detail: "avoid materialized repeat in final patch", category: "operation" },
      { id: "case_bias", label: "Case A: Bias", shortLabel: "bias", detail: "projected[B,T,O] + bias[O]", category: "contract" },
      { id: "case_position", label: "Case B: Position", shortLabel: "pos", detail: "tok_emb[B,T,C] + pos_emb[T,C]", category: "contract" },
      { id: "case_singleton", label: "Case C: Singleton", shortLabel: "single", detail: "hidden[B,T,C] + scale[1,T,1]", category: "contract" },
      { id: "case_mask", label: "Case D: Mask", shortLabel: "mask", detail: "scores[B,H,T,T] + mask[1,1,T,T]", category: "contract" },
      { id: "case_equal_dim", label: "Case E: Equal-dim trap", shortLabel: "4=4=4", detail: "hidden[4,4,4] + candidate[4]", category: "contract" },
      { id: "case_semantic_trace", label: "Case F: Semantic trace", shortLabel: "trace", detail: "cell source proves semantic alignment", category: "contract" },
      { id: "unsqueeze_leading_b", label: "Unsqueeze missing B", shortLabel: "unsq B", detail: "insert a leading singleton B axis without changing values", category: "rank" },
      { id: "unsqueeze_wrong_tail", label: "Unsqueeze trailing axis", shortLabel: "tail 1", detail: "wrong: inserts the singleton axis after C", category: "rank" },
      { id: "unsqueeze_keep_values", label: "Keep values unchanged", shortLabel: "same data", detail: "unsqueeze changes view shape, not tensor contents", category: "semantic" },
      { id: "view_no_copy", label: "Broadcast View", shortLabel: "view", detail: "logical broadcast view without allocating the full target tensor", category: "operation" },
      { id: "repeat_full_copy", label: "Repeat Copy", shortLabel: "repeat", detail: "wrong for S-rank: real full-size copies", category: "operation" },
      { id: "stride_zero_view", label: "Stride-zero reuse", shortLabel: "stride 0", detail: "reused cells point back to the same stored source value", category: "semantic" },
      { id: "residual_same_shape", label: "Residual same shape", shortLabel: "same", detail: "residual add normally requires identical hidden shapes", category: "contract" },
      { id: "residual_broadcast_wrong", label: "Residual broadcast", shortLabel: "bcast", detail: "wrong preview: residual stream is not a bias strip", category: "contract" },
      { id: "residual_preview_trace", label: "Residual trace", shortLabel: "trace", detail: "out[b,t,c] comes from both same-shape residual branches", category: "operation" },
      { id: "mask_value_large_negative", label: "Large negative mask", shortLabel: "-1e9", detail: "large negative additive mask suppresses future positions before softmax", category: "operation" },
      { id: "mask_value_zero_wrong", label: "Zero mask", shortLabel: "0", detail: "wrong for illegal positions; zero would not suppress future keys", category: "operation" },
      { id: "mask_softmax_probe", label: "Softmax effect trace", shortLabel: "softmax", detail: "after adding -1e9, softmax assigns effectively zero probability", category: "semantic" }
    ],
    slots: [
      {
        id: "cell_left_input",
        label: "A Input",
        nodeId: "scalar_a",
        focusNodeId: "scalar_a",
        emptyLabel: "?",
        correctTagIds: ["wire_scalar_a"],
        expected: "Scalar A feeds Add left input",
        successDetail: "Scalar A is connected to the Add Gate.",
        failureDetail: "Add Cell needs Scalar A on one input. Manual output does not count."
      },
      {
        id: "cell_right_input",
        label: "B Input",
        nodeId: "scalar_b",
        focusNodeId: "scalar_b",
        emptyLabel: "?",
        correctTagIds: ["wire_scalar_b"],
        expected: "Scalar B feeds Add right input",
        successDetail: "Scalar B is connected to the Add Gate.",
        failureDetail: "Add Gate requires two numeric inputs."
      },
      {
        id: "cell_trace_exact",
        label: "Cell Trace",
        nodeId: "cell_trace",
        focusNodeId: "cell_trace",
        emptyLabel: "?",
        correctTagIds: ["cell_trace_exact"],
        expected: "out[] = A[] + B[] = 7.0",
        successDetail: "The output cell is computed from both input cells.",
        failureDetail: "Trace the output source instead of typing a value into the result."
      },
      {
        id: "same_left_shape",
        label: "Left Shape",
        nodeId: "same_a",
        focusNodeId: "same_a",
        emptyLabel: "?",
        correctTagIds: ["same_shape_tc"],
        expected: "Residual A axes are [T,C]",
        successDetail: "Residual A exposes token and channel axes.",
        failureDetail: "Same-shape add starts from matching [T,C] axes, not swapped [C,T]."
      },
      {
        id: "same_right_shape",
        label: "Right Shape",
        nodeId: "same_b",
        focusNodeId: "same_b",
        emptyLabel: "?",
        correctTagIds: ["same_shape_tc"],
        expected: "Residual B axes are [T,C]",
        successDetail: "Residual B matches Residual A.",
        failureDetail: "Both same-shape operands must share the same axis order."
      },
      {
        id: "same_output_shape",
        label: "Output Shape",
        nodeId: "same_out",
        focusNodeId: "same_out",
        emptyLabel: "?",
        correctTagIds: ["same_output_tc"],
        expected: "output shape remains [T,C]",
        successDetail: "Same-shape add preserves T/C shape.",
        failureDetail: "Elementwise add does not consume or generate axes."
      },
      {
        id: "same_trace_cell",
        label: "Grid Trace",
        nodeId: "same_trace",
        focusNodeId: "same_trace",
        emptyLabel: "?",
        correctTagIds: ["same_trace_cell"],
        expected: "out[t,c] uses A[t,c] + B[t,c]",
        successDetail: "A traced cell uses matching coordinates from both inputs.",
        failureDetail: "Trace a matching cell; do not transpose or slide the source coordinates."
      },
      {
        id: "rule_vector_c",
        label: "Case A [C]",
        nodeId: "vector_c",
        focusNodeId: "broadcast_rail_lab",
        emptyLabel: "?",
        correctTagIds: ["align_c_right"],
        expected: "[C] right-aligns to target C",
        successDetail: "[C] becomes [1,1,C] and expands over B/T.",
        failureDetail: "[C] must align to channel C, not token T."
      },
      {
        id: "rule_matrix_tc",
        label: "Case B [T,C]",
        nodeId: "matrix_tc",
        focusNodeId: "broadcast_rail_lab",
        emptyLabel: "?",
        correctTagIds: ["insert_missing_b"],
        expected: "[T,C] becomes [1,T,C]",
        successDetail: "The missing B axis is treated as a singleton.",
        failureDetail: "Insert the missing axis before T/C; do not lose the C axis."
      },
      {
        id: "rule_singleton",
        label: "Case C [1,T,1]",
        nodeId: "singleton_scale",
        focusNodeId: "broadcast_rail_lab",
        emptyLabel: "?",
        correctTagIds: ["expand_singleton_bt"],
        expected: "singleton axes expand legally",
        successDetail: "Length-1 B and C axes expand to the target lengths.",
        failureDetail: "Only length-1 axes can expand when lengths differ."
      },
      {
        id: "rule_logical_view",
        label: "Ghost View",
        nodeId: "ghost_expansion",
        focusNodeId: "ghost_expansion",
        emptyLabel: "?",
        correctTagIds: ["logical_view"],
        expected: "broadcast is logical, not materialized repeat",
        successDetail: "Ghost expansion shows a logical broadcast view.",
        failureDetail: "Materialized repeat can match values but loses the intended broadcast model."
      },
      {
        id: "bias_axis_o",
        label: "Bias Axis",
        nodeId: "bias_o",
        focusNodeId: "bias_o",
        emptyLabel: "?",
        correctTagIds: ["axis_o"],
        expected: "bias aligns to O",
        successDetail: "Bias belongs to the output feature axis O.",
        failureDetail: "Linear bias shifts output features, not token positions."
      },
      {
        id: "bias_expand_bt",
        label: "Expansion",
        nodeId: "bias_rail",
        focusNodeId: "bias_rail",
        emptyLabel: "?",
        correctTagIds: ["expand_bt"],
        expected: "bias broadcasts over B and T",
        successDetail: "One bias strip is reused for every batch and token.",
        failureDetail: "Bias should be [1,1,O] against [B,T,O]."
      },
      {
        id: "bias_trace",
        label: "Bias Trace",
        nodeId: "bias_reference",
        focusNodeId: "bias_reference",
        emptyLabel: "?",
        correctTagIds: ["bias_cell_trace"],
        expected: "out[b,t,o] uses bias[o]",
        successDetail: "Cell trace confirms the bias source index.",
        failureDetail: "Trace out[b,t,o] to bias[o], not bias[t] or bias[b]."
      },
      {
        id: "position_align_tc",
        label: "Position Axes",
        nodeId: "pos_sheet",
        focusNodeId: "pos_sheet",
        emptyLabel: "?",
        correctTagIds: ["align_tc"],
        expected: "pos_emb aligns to T and C",
        successDetail: "Position sheet owns token position and channel axes.",
        failureDetail: "Position embedding must keep T. Treating it as [C] loses position information."
      },
      {
        id: "position_broadcast_b",
        label: "B Broadcast",
        nodeId: "position_rail",
        focusNodeId: "position_rail",
        emptyLabel: "?",
        correctTagIds: ["broadcast_b"],
        expected: "pos_emb broadcasts over B",
        successDetail: "The same position sheet is reused across batch samples.",
        failureDetail: "B is the missing axis; T and C should remain aligned."
      },
      {
        id: "position_keep_t",
        label: "Keep Position",
        nodeId: "position_trace",
        focusNodeId: "position_trace",
        emptyLabel: "?",
        correctTagIds: ["preserve_position_t"],
        expected: "pos_emb is not bias[C]",
        successDetail: "Cell trace shows position-specific values are preserved.",
        failureDetail: "You broadcast pos_emb as if it were bias[C]."
      },
      {
        id: "mask_tqtk_axes",
        label: "Mask Axes",
        nodeId: "mask_plate",
        focusNodeId: "mask_rail",
        emptyLabel: "?",
        correctTagIds: ["align_tqtk"],
        expected: "mask Tq/Tk align to scores Tq/Tk",
        successDetail: "Mask rows and columns align with query and key token axes.",
        failureDetail: "Swapping Tq/Tk reverses the future-token blocking pattern."
      },
      {
        id: "mask_expand_bh",
        label: "B/H Broadcast",
        nodeId: "mask_rail",
        focusNodeId: "mask_rail",
        emptyLabel: "?",
        correctTagIds: ["expand_bh"],
        expected: "mask singleton axes broadcast over B/H",
        successDetail: "The mask plate is reused for every batch and head.",
        failureDetail: "B/H are singleton broadcast axes, not token axes."
      },
      {
        id: "mask_additive",
        label: "Mask Operation",
        nodeId: "mask_add_gate",
        focusNodeId: "mask_add_gate",
        emptyLabel: "?",
        correctTagIds: ["add_negative_mask"],
        expected: "scores + negative mask before softmax",
        successDetail: "Illegal positions receive a large negative additive value.",
        failureDetail: "This stage expects additive mask, not multiplication."
      },
      {
        id: "mask_trace",
        label: "Illegal Cell",
        nodeId: "illegal_cell_checker",
        focusNodeId: "illegal_cell_checker",
        emptyLabel: "?",
        correctTagIds: ["mask_cell_trace"],
        expected: "future cell receives mask[0,0,q,k]",
        successDetail: "Cell trace confirms future positions are blocked.",
        failureDetail: "Trace a future cell such as q=2,k=3 to verify orientation."
      },
      {
        id: "trap_right_align",
        label: "Right Align Trap",
        nodeId: "trap_inspector",
        focusNodeId: "trap_inspector",
        emptyLabel: "?",
        correctTagIds: ["debug_right_align"],
        expected: "check raw right-alignment first",
        successDetail: "The debugger checks right-alignment before semantic labels.",
        failureDetail: "Start by aligning ranks and trailing axes before patching semantics."
      },
      {
        id: "trap_bt_swap",
        label: "B/T Swap",
        nodeId: "semantic_warning",
        focusNodeId: "semantic_warning",
        emptyLabel: "?",
        correctTagIds: ["debug_bt_swap"],
        expected: "catch shape-valid B/T swaps",
        successDetail: "Equal-sized axes no longer hide a B/T semantic swap.",
        failureDetail: "Shape can pass while B and T are semantically reversed."
      },
      {
        id: "trap_pos_bias",
        label: "Position-as-Bias",
        nodeId: "trace_probe_04",
        focusNodeId: "trace_probe_04",
        emptyLabel: "?",
        correctTagIds: ["debug_pos_bias"],
        expected: "pos_emb[T,C] must not collapse to bias[C]",
        successDetail: "Cell trace catches position information being lost.",
        failureDetail: "If pos_emb only varies by C, you turned it into a bias."
      },
      {
        id: "trap_no_repeat",
        label: "No Repeat",
        nodeId: "trap_patch",
        focusNodeId: "trap_patch",
        emptyLabel: "?",
        correctTagIds: ["debug_no_repeat"],
        expected: "prefer logical broadcast view",
        successDetail: "The final patch keeps broadcast logical.",
        failureDetail: "Use Ghost Expansion / logical broadcast instead of real repeat copies."
      },
      {
        id: "bonus_unsqueeze_axis",
        label: "Unsqueeze Axis",
        nodeId: "broadcast_rail_lab",
        focusNodeId: "broadcast_rail_lab",
        emptyLabel: "?",
        correctTagIds: ["unsqueeze_leading_b"],
        expected: "[T,C] -> [1,T,C]",
        successDetail: "Unsqueeze inserts the missing leading B axis.",
        failureDetail: "Insert the singleton axis before T/C; trailing insertion changes the broadcast contract."
      },
      {
        id: "bonus_unsqueeze_values",
        label: "Value Invariant",
        nodeId: "ghost_expansion",
        focusNodeId: "ghost_expansion",
        emptyLabel: "?",
        correctTagIds: ["unsqueeze_keep_values"],
        expected: "unsqueeze does not modify stored values",
        successDetail: "Only the view shape changes; the stored tensor values are unchanged.",
        failureDetail: "Unsqueeze should not rewrite values or reorder cells."
      },
      {
        id: "bonus_no_copy_view",
        label: "No-copy View",
        nodeId: "ghost_expansion",
        focusNodeId: "ghost_expansion",
        emptyLabel: "?",
        correctTagIds: ["view_no_copy"],
        expected: "broadcast uses a logical view",
        successDetail: "Broadcast expansion is represented as a view.",
        failureDetail: "Materialized repeat can match values but fails the efficiency contract."
      },
      {
        id: "bonus_no_copy_stride",
        label: "Source Reuse",
        nodeId: "plan_checker",
        focusNodeId: "plan_checker",
        emptyLabel: "?",
        correctTagIds: ["stride_zero_view"],
        expected: "expanded cells reuse the same source value",
        successDetail: "Repeated logical cells point back to the same source storage.",
        failureDetail: "A no-copy broadcast should prove source reuse, not allocate repeated storage."
      },
      {
        id: "bonus_residual_same",
        label: "Residual Shape",
        nodeId: "same_add_gate",
        focusNodeId: "same_add_gate",
        emptyLabel: "?",
        correctTagIds: ["residual_same_shape"],
        expected: "residual branches share [B,T,C]",
        successDetail: "Residual add preview uses identical hidden shapes.",
        failureDetail: "Residual add should not rely on broadcast to hide a branch shape mismatch."
      },
      {
        id: "bonus_residual_trace",
        label: "Residual Trace",
        nodeId: "same_trace",
        focusNodeId: "same_trace",
        emptyLabel: "?",
        correctTagIds: ["residual_preview_trace"],
        expected: "out[b,t,c] uses both residual branches",
        successDetail: "The preview trace proves same-coordinate residual addition.",
        failureDetail: "Trace one cell from both same-shape residual inputs."
      },
      {
        id: "bonus_mask_value",
        label: "Mask Value",
        nodeId: "mask_add_gate",
        focusNodeId: "mask_add_gate",
        emptyLabel: "?",
        correctTagIds: ["mask_value_large_negative"],
        expected: "illegal positions receive a large negative value",
        successDetail: "The additive mask uses a large negative value before softmax.",
        failureDetail: "Zero does not block illegal future positions in a pre-softmax additive mask."
      },
      {
        id: "bonus_mask_softmax",
        label: "Softmax Effect",
        nodeId: "illegal_cell_checker",
        focusNodeId: "illegal_cell_checker",
        emptyLabel: "?",
        correctTagIds: ["mask_softmax_probe"],
        expected: "softmax probability becomes effectively zero",
        successDetail: "The mask value experiment confirms the post-softmax effect.",
        failureDetail: "Probe the illegal cell after additive mask and softmax."
      },
      {
        id: "gauntlet_bias",
        label: "Case A",
        nodeId: "broadcast_gauntlet_cases",
        focusNodeId: "broadcast_gauntlet_cases",
        emptyLabel: "?",
        correctTagIds: ["case_bias"],
        expected: "bias add hidden case passes",
        successDetail: "Bias add case armed.",
        failureDetail: "Case A should verify projected[B,T,O] + bias[O]."
      },
      {
        id: "gauntlet_position",
        label: "Case B",
        nodeId: "broadcast_gauntlet_cases",
        focusNodeId: "broadcast_contract_terminal",
        emptyLabel: "?",
        correctTagIds: ["case_position"],
        expected: "position add hidden case passes",
        successDetail: "Position add case armed.",
        failureDetail: "Case B should verify tok_emb[B,T,C] + pos_emb[T,C]."
      },
      {
        id: "gauntlet_singleton",
        label: "Case C",
        nodeId: "broadcast_gauntlet_cases",
        focusNodeId: "broadcast_contract_terminal",
        emptyLabel: "?",
        correctTagIds: ["case_singleton"],
        expected: "singleton broadcast hidden case passes",
        successDetail: "Singleton case armed.",
        failureDetail: "Case C should verify [1,T,1] expansion."
      },
      {
        id: "gauntlet_mask",
        label: "Case D",
        nodeId: "broadcast_gauntlet_cases",
        focusNodeId: "hidden_broadcast_reference",
        emptyLabel: "?",
        correctTagIds: ["case_mask"],
        expected: "mask add hidden case passes",
        successDetail: "Mask case armed.",
        failureDetail: "Case D should verify mask[1,1,T,T] over scores[B,H,T,T]."
      },
      {
        id: "gauntlet_equal_dim",
        label: "Case E",
        nodeId: "hidden_broadcast_reference",
        focusNodeId: "hidden_broadcast_reference",
        emptyLabel: "?",
        correctTagIds: ["case_equal_dim"],
        expected: "equal-dimension trap passes",
        successDetail: "Equal-dimension trap is covered.",
        failureDetail: "Case E catches dimension-size guessing such as hidden[4,4,4] + candidate[4]."
      },
      {
        id: "gauntlet_semantic_trace",
        label: "Case F",
        nodeId: "broadcast_gauntlet_result",
        focusNodeId: "broadcast_gauntlet_result",
        emptyLabel: "?",
        correctTagIds: ["case_semantic_trace"],
        expected: "semantic cell trace passes",
        successDetail: "Semantic trace case is armed.",
        failureDetail: "Final case should prove source indices, not just output shape."
      }
    ],
    probes: [
      {
        id: "add_probe",
        label: "Add Probe",
        detail: "shows cell provenance for scalar and same-shape add",
        budgetCost: 1,
        observations: {
          cell_trace_exact: {
            id: "probe_add_cell",
            title: "One output cell has two source cells",
            detail: "The output is computed by Add Gate, not manually entered.",
            evidence: ["A[] = 2.0", "B[] = 5.0", "out[] = 7.0"],
            possibleSemantic: "cell trace",
            confidence: "high"
          },
          same_trace_cell: {
            id: "probe_same_cell",
            title: "Same coordinates meet",
            detail: "Same-shape add pairs cells by the exact same T/C coordinate.",
            evidence: ["out[1,2] = A[1,2] + B[1,2]", "shape remains [T,C]"],
            possibleSemantic: "same-shape add",
            confidence: "high"
          },
          bonus_residual_trace: {
            id: "probe_residual_trace",
            title: "Residual add is same-coordinate add",
            detail: "Residual branches should already share the hidden tensor shape.",
            evidence: ["left[b,t,c] + right[b,t,c]", "no broadcast needed for normal residual add"],
            possibleSemantic: "residual add",
            confidence: "medium"
          }
        }
      },
      {
        id: "broadcast_probe",
        label: "Broadcast Probe",
        detail: "shows missing-axis and singleton-axis broadcast plans",
        budgetCost: 1,
        observations: {
          rule_vector_c: {
            id: "probe_vector_c",
            title: "[C] pads with leading singleton axes",
            detail: "Right-alignment turns [C] into [1,1,C].",
            evidence: ["target: [B,T,C]", "input: [C]", "view: [1,1,C]"],
            possibleSemantic: "right-align [C]",
            confidence: "high"
          },
          rule_matrix_tc: {
            id: "probe_matrix_tc",
            title: "[T,C] is missing B",
            detail: "The missing leading axis is treated as length 1.",
            evidence: ["target: [B,T,C]", "input: [T,C]", "view: [1,T,C]"],
            possibleSemantic: "insert missing B",
            confidence: "high"
          },
          rule_singleton: {
            id: "probe_singleton",
            title: "Singleton axes can expand",
            detail: "Length-1 B and C axes reuse the same source values.",
            evidence: ["input: [1,T,1]", "plan: [*,T,*]"],
            possibleSemantic: "singleton expansion",
            confidence: "high"
          },
          rule_logical_view: {
            id: "probe_logical",
            title: "Ghost copies are not real storage",
            detail: "Broadcast view repeats values only at access time.",
            evidence: ["real storage stays small", "logical shape matches target"],
            possibleSemantic: "logical view",
            confidence: "medium"
          },
          bonus_unsqueeze_axis: {
            id: "probe_unsqueeze_axis",
            title: "Unsqueeze inserts a singleton axis",
            detail: "The missing B axis is inserted before T/C.",
            evidence: ["input: [T,C]", "view: [1,T,C]", "values unchanged"],
            possibleSemantic: "unsqueeze leading B",
            confidence: "high"
          },
          bonus_unsqueeze_values: {
            id: "probe_unsqueeze_values",
            title: "Unsqueeze keeps storage intact",
            detail: "The same values appear at the same T/C coordinates after the view change.",
            evidence: ["old[t,c] == view[0,t,c]", "rank changes, values do not"],
            possibleSemantic: "view reshape",
            confidence: "high"
          }
        }
      },
      {
        id: "llm_broadcast_probe",
        label: "LLM Broadcast Probe",
        detail: "checks bias and position broadcast source indices",
        budgetCost: 1,
        observations: {
          bias_axis_o: {
            id: "probe_bias_axis",
            title: "Bias belongs to output features",
            detail: "The bias strip has one scalar per O channel.",
            evidence: ["projected: [B,T,O]", "bias: [O]", "view: [1,1,O]"],
            possibleSemantic: "O axis",
            confidence: "high"
          },
          position_align_tc: {
            id: "probe_position_axis",
            title: "Position sheet owns T and C",
            detail: "Each token position has a full C-wide vector.",
            evidence: ["tok_emb: [B,T,C]", "pos_emb: [T,C]", "view: [1,T,C]"],
            possibleSemantic: "[T,C]",
            confidence: "high"
          },
          position_keep_t: {
            id: "probe_position_trace",
            title: "Position is not channel bias",
            detail: "A traced cell must use the t-specific row of pos_emb.",
            evidence: ["hidden[b,t,c] uses pos_emb[t,c]", "not pos_emb[c]"],
            possibleSemantic: "keep T",
            confidence: "high"
          }
        }
      },
      {
        id: "mask_probe",
        label: "Mask Probe",
        detail: "checks additive attention mask alignment and illegal cells",
        budgetCost: 1,
        observations: {
          mask_tqtk_axes: {
            id: "probe_mask_axes",
            title: "Mask rows and columns are not interchangeable",
            detail: "Query rows and key columns decide which future cells are illegal.",
            evidence: ["scores: [B,H,Tq,Tk]", "mask: [1,1,Tq,Tk]"],
            possibleSemantic: "Tq/Tk",
            confidence: "high"
          },
          mask_expand_bh: {
            id: "probe_mask_bh",
            title: "B/H are singleton broadcast axes",
            detail: "The same causal mask is reused for every batch/head layer.",
            evidence: ["mask view: [1,1,Tq,Tk]", "target: [B,H,Tq,Tk]"],
            possibleSemantic: "expand B/H",
            confidence: "high"
          },
          mask_additive: {
            id: "probe_mask_add",
            title: "Mask is added before softmax",
            detail: "A large negative value makes future tokens effectively impossible.",
            evidence: ["illegal cell receives -1e9", "softmax comes later"],
            possibleSemantic: "additive mask",
            confidence: "high"
          },
          bonus_mask_value: {
            id: "probe_mask_value",
            title: "Large negative means effectively impossible",
            detail: "The illegal logit is pushed far below legal logits before softmax.",
            evidence: ["logit + (-1e9)", "probability rounds to 0"],
            possibleSemantic: "mask value",
            confidence: "high"
          },
          bonus_mask_softmax: {
            id: "probe_mask_softmax",
            title: "Softmax confirms the mask effect",
            detail: "After softmax, masked future cells contribute no attention mass.",
            evidence: ["future probability ~= 0", "row mass stays on legal keys"],
            possibleSemantic: "softmax effect",
            confidence: "high"
          }
        }
      },
      {
        id: "trap_probe",
        label: "Trap Probe",
        detail: "diagnoses shape-valid but semantically wrong broadcast plans",
        budgetCost: 1,
        observations: {
          trap_bt_swap: {
            id: "probe_bt_swap",
            title: "Equal-size axes can lie",
            detail: "A B/T swap may keep shape valid while changing the meaning of every cell.",
            evidence: ["hidden[4,4,4]", "size cannot identify B/T/C"],
            possibleSemantic: "semantic trap",
            confidence: "high"
          },
          trap_pos_bias: {
            id: "probe_pos_bias",
            title: "Position collapsed into bias",
            detail: "If T is lost, every token position gets the same offset.",
            evidence: ["pos_emb[T,C]", "wrong view: [1,1,C]"],
            possibleSemantic: "pos != bias",
            confidence: "high"
          },
          trap_no_repeat: {
            id: "probe_no_repeat",
            title: "Materialized repeat is inefficient",
            detail: "The values may match, but the memory model is not a broadcast view.",
            evidence: ["full-size copy detected", "logical view expected"],
            possibleSemantic: "no repeat",
            confidence: "medium"
          },
          gauntlet_equal_dim: {
            id: "probe_equal_dim",
            title: "Final hidden trap changes only semantics",
            detail: "The all-equal shape forces cell trace to prove the contract.",
            evidence: ["candidate[4]", "target[4,4,4]", "which axis is 4?"],
            possibleSemantic: "semantic trace",
            confidence: "high"
          },
          bonus_no_copy_view: {
            id: "probe_no_copy_view",
            title: "Broadcast view avoids full allocation",
            detail: "A logical view can present the target shape while storing only the original tensor.",
            evidence: ["stored cells stay small", "expanded cells reuse sources"],
            possibleSemantic: "no-copy view",
            confidence: "medium"
          },
          bonus_no_copy_stride: {
            id: "probe_no_copy_stride",
            title: "Repeated positions reuse source cells",
            detail: "The same source value is addressed from many broadcasted coordinates.",
            evidence: ["view[b,t,c] -> source[t,c]", "no full repeated buffer"],
            possibleSemantic: "source reuse",
            confidence: "medium"
          }
        }
      }
    ],
    checks: [
      {
        id: "add_cell_contract",
        title: "0-4A Add Cell",
        group: "visible",
        slotIds: ["cell_left_input", "cell_right_input", "cell_trace_exact"],
        expected: "A[] + B[] -> out[] exact match",
        passDetail: "Add Cell computes one scalar output from two scalar inputs.",
        failDetail: "Add Cell contract is incomplete.",
        focusNodeId: "add_gate_cell"
      },
      {
        id: "same_shape_contract",
        title: "0-4B Same-Shape Add",
        group: "visible",
        slotIds: ["same_left_shape", "same_right_shape", "same_output_shape", "same_trace_cell"],
        expected: "A[T,C] + B[T,C] -> out[T,C]",
        passDetail: "Same-shape add preserves axes and pairs matching cells.",
        failDetail: "Same-shape add contract is wrong.",
        focusNodeId: "same_add_gate"
      },
      {
        id: "broadcast_rule_lab_contract",
        title: "0-4C Broadcast Rule Lab",
        group: "visible",
        slotIds: ["rule_vector_c", "rule_matrix_tc", "rule_singleton", "rule_logical_view"],
        expected: "[C], [T,C], and [1,T,1] broadcast plans are valid",
        passDetail: "Missing-axis, singleton-axis, and logical-view broadcast plans pass.",
        failDetail: "Broadcast Rule Lab plan is incomplete.",
        focusNodeId: "broadcast_rail_lab"
      },
      {
        id: "bias_add_contract",
        title: "0-4D Bias Add",
        group: "behavior",
        slotIds: ["bias_axis_o", "bias_expand_bt", "bias_trace"],
        expected: "projected[B,T,O] + bias[O] -> out[B,T,O]",
        passDetail: "Bias is aligned to O and broadcast over B/T.",
        failDetail: "Bias Add contract is wrong.",
        blockedDetail: "Bias Add is blocked until Add Cell, same-shape add, and Broadcast Rule Lab pass.",
        focusNodeId: "bias_rail"
      },
      {
        id: "position_add_contract",
        title: "0-4E Position Add",
        group: "behavior",
        slotIds: ["position_align_tc", "position_broadcast_b", "position_keep_t"],
        expected: "tok_emb[B,T,C] + pos_emb[T,C] -> hidden[B,T,C]",
        passDetail: "Position sheet keeps T/C and broadcasts only over B.",
        failDetail: "Position Add contract is wrong.",
        blockedDetail: "Position Add is blocked until earlier broadcast contracts pass.",
        focusNodeId: "position_rail"
      },
      {
        id: "mask_add_contract",
        title: "0-4F Mask Add",
        group: "behavior",
        slotIds: ["mask_tqtk_axes", "mask_expand_bh", "mask_additive", "mask_trace"],
        expected: "scores[B,H,Tq,Tk] + mask[1,1,Tq,Tk] -> masked_scores[B,H,Tq,Tk]",
        passDetail: "Mask Add aligns Tq/Tk, broadcasts over B/H, and blocks future cells additively.",
        failDetail: "Mask Add contract is wrong.",
        blockedDetail: "Mask Add is blocked until position and bias broadcast contracts pass.",
        focusNodeId: "mask_rail"
      },
      {
        id: "broadcast_trap_debugger_contract",
        title: "0-4G Broadcast Trap Debugger",
        group: "behavior",
        slotIds: ["trap_right_align", "trap_bt_swap", "trap_pos_bias", "trap_no_repeat"],
        expected: "right-align, B/T swap, position-as-bias, and repeat traps diagnosed",
        passDetail: "Broadcast debugger catches shape-valid semantic traps.",
        failDetail: "Broadcast trap debugger is incomplete.",
        blockedDetail: "Trap debugger is blocked until core LLM broadcast cases pass.",
        focusNodeId: "trap_reference_04"
      },
      {
        id: "bonus_unsqueeze_lab",
        title: "Bonus A Unsqueeze Lab",
        group: "behavior",
        slotIds: ["bonus_unsqueeze_axis", "bonus_unsqueeze_values"],
        expected: "[T,C] is viewed as [1,T,C] without changing values",
        passDetail: "Unsqueeze Lab confirms singleton-axis insertion without value edits.",
        failDetail: "Unsqueeze Lab is incomplete.",
        blockedDetail: "Unsqueeze Lab is blocked until core broadcast traps pass.",
        focusNodeId: "broadcast_rail_lab"
      },
      {
        id: "bonus_no_copy_broadcast",
        title: "Bonus B No-Copy Broadcast",
        group: "behavior",
        slotIds: ["bonus_no_copy_view", "bonus_no_copy_stride"],
        expected: "broadcast is represented as a logical view, not materialized repeat",
        passDetail: "No-Copy Broadcast confirms source reuse and avoids full repeated buffers.",
        failDetail: "No-Copy Broadcast is incomplete.",
        blockedDetail: "No-Copy Broadcast is blocked until Unsqueeze Lab passes.",
        focusNodeId: "ghost_expansion"
      },
      {
        id: "bonus_residual_preview",
        title: "Bonus C Residual Add Preview",
        group: "behavior",
        slotIds: ["bonus_residual_same", "bonus_residual_trace"],
        expected: "residual branches add with identical [B,T,C] coordinates",
        passDetail: "Residual Add Preview confirms same-shape residual addition.",
        failDetail: "Residual Add Preview is incomplete.",
        blockedDetail: "Residual Add Preview is blocked until no-copy broadcast passes.",
        focusNodeId: "same_add_gate"
      },
      {
        id: "bonus_mask_value_experiment",
        title: "Bonus D Mask Value Experiment",
        group: "behavior",
        slotIds: ["bonus_mask_value", "bonus_mask_softmax"],
        expected: "large negative additive mask drives illegal softmax probability to zero",
        passDetail: "Mask Value Experiment confirms why the mask uses a large negative value.",
        failDetail: "Mask Value Experiment is incomplete.",
        blockedDetail: "Mask Value Experiment is blocked until residual preview passes.",
        focusNodeId: "mask_add_gate"
      },
      {
        id: "broadcast_reference_allclose",
        title: "reference broadcast allclose",
        group: "reference",
        slotIds: [
          "cell_trace_exact",
          "same_trace_cell",
          "rule_logical_view",
          "bias_trace",
          "position_keep_t",
          "mask_trace",
          "trap_no_repeat"
        ],
        expected: "all visible and behavior reference traces match",
        passDetail: "Reference traces match for scalar, same-shape, bias, position, mask, and trap cases.",
        failDetail: "One or more broadcast reference traces diverged.",
        blockedDetail: "Reference checks are blocked until visible and behavior contracts pass.",
        focusNodeId: "hidden_broadcast_reference"
      },
      {
        id: "broadcast_gauntlet_cases",
        title: "0-4X Broadcast Gauntlet",
        group: "hidden",
        slotIds: [
          "gauntlet_bias",
          "gauntlet_position",
          "gauntlet_singleton",
          "gauntlet_mask",
          "gauntlet_equal_dim",
          "gauntlet_semantic_trace"
        ],
        expected: "bias, position, singleton, mask, equal-dim, and semantic trace hidden cases pass",
        passDetail: "The Broadcast Add contract generalizes across all hidden cases.",
        failDetail: "Hidden Broadcast Gauntlet failed.",
        blockedDetail: "Hidden tests are blocked until reference broadcast checks pass.",
        focusNodeId: "broadcast_gauntlet_result"
      }
    ],
    hiddenCases: [
      "Case A: projected[2,3,5] + bias[5]",
      "Case B: tok_emb[2,4,6] + pos_emb[4,6]",
      "Case C: hidden[3,5,7] + scale[1,5,1]",
      "Case D: scores[2,3,4,4] + mask[1,1,4,4]",
      "Case E: hidden[4,4,4] + candidate[4] equal-dimension trap",
      "Case F: shape-valid semantic trap validated by cell trace"
    ],
    successSummary:
      "Broadcast Add repaired: Add Cell, same-shape add, broadcast rules, bias add, position add, mask add, trap debugger, bonus labs, and hidden gauntlet all pass."
  },
  traceSteps: [
    { id: "04_step_add_cell", title: "Add Cell", state: "warn", detail: "[] + [] -> []", selectNodeId: "add_gate_cell" },
    { id: "04_step_same", title: "Same Shape", state: "warn", detail: "[T,C]+[T,C]", selectNodeId: "same_add_gate" },
    { id: "04_step_rule", title: "Broadcast Rule", state: "warn", detail: "missing / singleton axes", selectNodeId: "broadcast_rail_lab" },
    { id: "04_step_bias", title: "Bias", state: "warn", detail: "[B,T,O]+[O]", selectNodeId: "bias_rail" },
    { id: "04_step_position", title: "Position", state: "warn", detail: "[B,T,C]+[T,C]", selectNodeId: "position_rail" },
    { id: "04_step_mask", title: "Mask", state: "warn", detail: "[B,H,T,T]+[1,1,T,T]", selectNodeId: "mask_rail" },
    { id: "04_step_debug", title: "Trap Debugger", state: "warn", detail: "shape + semantics + trace", selectNodeId: "trap_reference_04" },
    { id: "04_step_bonus", title: "Bonus Labs", state: "warn", detail: "unsqueeze / no-copy / residual / mask value", selectNodeId: "ghost_expansion" },
    { id: "04_step_gauntlet", title: "Gauntlet", state: "warn", detail: "hidden cases", selectNodeId: "broadcast_gauntlet_result" }
  ]
};
