from __future__ import annotations

from typing import Any

from server.core.content import load_artifact_manifest, load_sample_outputs
from server.core.progress_store import get_progress


def list_artifacts() -> list[dict[str, Any]]:
    progress = get_progress()
    unlocked = set(progress["unlocked_artifacts"])
    return [
        {
            **artifact,
            "unlocked": artifact["id"] in unlocked,
            "source": "sample_outputs",
        }
        for artifact in load_artifact_manifest()["artifacts"]
    ]


def _fallback_output(artifact_id: str, prompt: str) -> dict[str, str]:
    samples = load_sample_outputs()
    for row in samples:
        if row["artifact_id"] == artifact_id and row["prompt"] == prompt:
            return {
                "output": row["output"],
                "notes": row.get("notes", ""),
                "source": "sample_outputs",
            }

    if artifact_id == "sft":
        if "23 + 48" in prompt:
            return {
                "output": "<think>23 + 48 = 71。</think>\n<answer>71</answer>",
                "notes": "Generated by MVP fallback rule for SFT.",
                "source": "fallback_rule",
            }
        return {
            "output": f"这是一个指令模型回答：{prompt}",
            "notes": "Generated by MVP fallback rule for SFT.",
            "source": "fallback_rule",
        }

    return {
        "output": f"{prompt} ... continues with related training text, but does not reliably follow instructions.",
        "notes": "Generated by MVP fallback rule for base model.",
        "source": "fallback_rule",
    }


def compare_outputs(prompt: str, artifact_ids: list[str]) -> dict[str, Any]:
    artifacts = {artifact["id"]: artifact for artifact in list_artifacts()}
    rows = []
    for artifact_id in artifact_ids:
        artifact = artifacts.get(artifact_id)
        if not artifact:
            rows.append(
                {
                    "artifact_id": artifact_id,
                    "display_name": artifact_id,
                    "output": "Artifact is not registered.",
                    "notes": "",
                    "source": "missing",
                    "unlocked": False,
                }
            )
            continue
        fallback = _fallback_output(artifact_id, prompt)
        rows.append(
            {
                "artifact_id": artifact_id,
                "display_name": artifact["display_name"],
                "stage": artifact["stage"],
                "output": fallback["output"],
                "notes": fallback["notes"],
                "source": fallback["source"],
                "unlocked": artifact["unlocked"],
            }
        )
    return {"prompt": prompt, "results": rows}
